// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.aware.model;

/**
 * <pre>
 * Represents an arbitrary http(s) payload of requests / responses.
 * </pre>
 *
 * Protobuf type {@code org.aware.model.HttpPayload}
 */
public final class HttpPayload extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.aware.model.HttpPayload)
    HttpPayloadOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HttpPayload.newBuilder() to construct.
  private HttpPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HttpPayload() {
    httpMethod_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HttpPayload();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.aware.model.Model.internal_static_org_aware_model_HttpPayload_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetHeaderMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.aware.model.Model.internal_static_org_aware_model_HttpPayload_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.aware.model.HttpPayload.class, org.aware.model.HttpPayload.Builder.class);
  }

  private int bitField0_;
  private int bodyCase_ = 0;
  private java.lang.Object body_;
  public enum BodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    JSON_BODY(2),
    HTTP_GET_BODY(4),
    TEXT_BODY(5),
    HTML_BODY(6),
    XML_BODY(7),
    HTTP_FORM_DATA_BODY(8),
    HTTP_FORM_URLENCODED_BODY(11),
    BINARY_DATA_BODY(9),
    BODY_NOT_SET(0);
    private final int value;
    private BodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static BodyCase forNumber(int value) {
      switch (value) {
        case 2: return JSON_BODY;
        case 4: return HTTP_GET_BODY;
        case 5: return TEXT_BODY;
        case 6: return HTML_BODY;
        case 7: return XML_BODY;
        case 8: return HTTP_FORM_DATA_BODY;
        case 11: return HTTP_FORM_URLENCODED_BODY;
        case 9: return BINARY_DATA_BODY;
        case 0: return BODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public BodyCase
  getBodyCase() {
    return BodyCase.forNumber(
        bodyCase_);
  }

  public static final int HEADER_MAP_FIELD_NUMBER = 1;
  private static final class HeaderMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.aware.model.Model.internal_static_org_aware_model_HttpPayload_HeaderMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> headerMap_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetHeaderMap() {
    if (headerMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          HeaderMapDefaultEntryHolder.defaultEntry);
    }
    return headerMap_;
  }

  public int getHeaderMapCount() {
    return internalGetHeaderMap().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */

  @java.lang.Override
  public boolean containsHeaderMap(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetHeaderMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getHeaderMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getHeaderMap() {
    return getHeaderMapMap();
  }
  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getHeaderMapMap() {
    return internalGetHeaderMap().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */
  @java.lang.Override

  public java.lang.String getHeaderMapOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetHeaderMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */
  @java.lang.Override

  public java.lang.String getHeaderMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetHeaderMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int HTTP_METHOD_FIELD_NUMBER = 3;
  private volatile java.lang.Object httpMethod_;
  /**
   * <pre>
   * Only applicable for request payloads.
   * </pre>
   *
   * <code>optional string http_method = 3;</code>
   * @return Whether the httpMethod field is set.
   */
  @java.lang.Override
  public boolean hasHttpMethod() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Only applicable for request payloads.
   * </pre>
   *
   * <code>optional string http_method = 3;</code>
   * @return The httpMethod.
   */
  @java.lang.Override
  public java.lang.String getHttpMethod() {
    java.lang.Object ref = httpMethod_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      httpMethod_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Only applicable for request payloads.
   * </pre>
   *
   * <code>optional string http_method = 3;</code>
   * @return The bytes for httpMethod.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHttpMethodBytes() {
    java.lang.Object ref = httpMethod_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      httpMethod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSE_CODE_FIELD_NUMBER = 12;
  private int responseCode_;
  /**
   * <pre>
   * Only applicable for response payloads.
   * </pre>
   *
   * <code>optional int32 response_code = 12;</code>
   * @return Whether the responseCode field is set.
   */
  @java.lang.Override
  public boolean hasResponseCode() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Only applicable for response payloads.
   * </pre>
   *
   * <code>optional int32 response_code = 12;</code>
   * @return The responseCode.
   */
  @java.lang.Override
  public int getResponseCode() {
    return responseCode_;
  }

  public static final int JSON_BODY_FIELD_NUMBER = 2;
  /**
   * <code>string json_body = 2;</code>
   * @return Whether the jsonBody field is set.
   */
  public boolean hasJsonBody() {
    return bodyCase_ == 2;
  }
  /**
   * <code>string json_body = 2;</code>
   * @return The jsonBody.
   */
  public java.lang.String getJsonBody() {
    java.lang.Object ref = "";
    if (bodyCase_ == 2) {
      ref = body_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bodyCase_ == 2) {
        body_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string json_body = 2;</code>
   * @return The bytes for jsonBody.
   */
  public com.google.protobuf.ByteString
      getJsonBodyBytes() {
    java.lang.Object ref = "";
    if (bodyCase_ == 2) {
      ref = body_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (bodyCase_ == 2) {
        body_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HTTP_GET_BODY_FIELD_NUMBER = 4;
  /**
   * <code>.org.aware.model.HttpGetBody http_get_body = 4;</code>
   * @return Whether the httpGetBody field is set.
   */
  @java.lang.Override
  public boolean hasHttpGetBody() {
    return bodyCase_ == 4;
  }
  /**
   * <code>.org.aware.model.HttpGetBody http_get_body = 4;</code>
   * @return The httpGetBody.
   */
  @java.lang.Override
  public org.aware.model.HttpGetBody getHttpGetBody() {
    if (bodyCase_ == 4) {
       return (org.aware.model.HttpGetBody) body_;
    }
    return org.aware.model.HttpGetBody.getDefaultInstance();
  }
  /**
   * <code>.org.aware.model.HttpGetBody http_get_body = 4;</code>
   */
  @java.lang.Override
  public org.aware.model.HttpGetBodyOrBuilder getHttpGetBodyOrBuilder() {
    if (bodyCase_ == 4) {
       return (org.aware.model.HttpGetBody) body_;
    }
    return org.aware.model.HttpGetBody.getDefaultInstance();
  }

  public static final int TEXT_BODY_FIELD_NUMBER = 5;
  /**
   * <code>string text_body = 5;</code>
   * @return Whether the textBody field is set.
   */
  public boolean hasTextBody() {
    return bodyCase_ == 5;
  }
  /**
   * <code>string text_body = 5;</code>
   * @return The textBody.
   */
  public java.lang.String getTextBody() {
    java.lang.Object ref = "";
    if (bodyCase_ == 5) {
      ref = body_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bodyCase_ == 5) {
        body_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string text_body = 5;</code>
   * @return The bytes for textBody.
   */
  public com.google.protobuf.ByteString
      getTextBodyBytes() {
    java.lang.Object ref = "";
    if (bodyCase_ == 5) {
      ref = body_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (bodyCase_ == 5) {
        body_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HTML_BODY_FIELD_NUMBER = 6;
  /**
   * <code>string html_body = 6;</code>
   * @return Whether the htmlBody field is set.
   */
  public boolean hasHtmlBody() {
    return bodyCase_ == 6;
  }
  /**
   * <code>string html_body = 6;</code>
   * @return The htmlBody.
   */
  public java.lang.String getHtmlBody() {
    java.lang.Object ref = "";
    if (bodyCase_ == 6) {
      ref = body_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bodyCase_ == 6) {
        body_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string html_body = 6;</code>
   * @return The bytes for htmlBody.
   */
  public com.google.protobuf.ByteString
      getHtmlBodyBytes() {
    java.lang.Object ref = "";
    if (bodyCase_ == 6) {
      ref = body_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (bodyCase_ == 6) {
        body_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int XML_BODY_FIELD_NUMBER = 7;
  /**
   * <code>string xml_body = 7;</code>
   * @return Whether the xmlBody field is set.
   */
  public boolean hasXmlBody() {
    return bodyCase_ == 7;
  }
  /**
   * <code>string xml_body = 7;</code>
   * @return The xmlBody.
   */
  public java.lang.String getXmlBody() {
    java.lang.Object ref = "";
    if (bodyCase_ == 7) {
      ref = body_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bodyCase_ == 7) {
        body_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string xml_body = 7;</code>
   * @return The bytes for xmlBody.
   */
  public com.google.protobuf.ByteString
      getXmlBodyBytes() {
    java.lang.Object ref = "";
    if (bodyCase_ == 7) {
      ref = body_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (bodyCase_ == 7) {
        body_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HTTP_FORM_DATA_BODY_FIELD_NUMBER = 8;
  /**
   * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
   * @return Whether the httpFormDataBody field is set.
   */
  @java.lang.Override
  public boolean hasHttpFormDataBody() {
    return bodyCase_ == 8;
  }
  /**
   * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
   * @return The httpFormDataBody.
   */
  @java.lang.Override
  public org.aware.model.HttpFormDataBody getHttpFormDataBody() {
    if (bodyCase_ == 8) {
       return (org.aware.model.HttpFormDataBody) body_;
    }
    return org.aware.model.HttpFormDataBody.getDefaultInstance();
  }
  /**
   * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
   */
  @java.lang.Override
  public org.aware.model.HttpFormDataBodyOrBuilder getHttpFormDataBodyOrBuilder() {
    if (bodyCase_ == 8) {
       return (org.aware.model.HttpFormDataBody) body_;
    }
    return org.aware.model.HttpFormDataBody.getDefaultInstance();
  }

  public static final int HTTP_FORM_URLENCODED_BODY_FIELD_NUMBER = 11;
  /**
   * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
   * @return Whether the httpFormUrlencodedBody field is set.
   */
  @java.lang.Override
  public boolean hasHttpFormUrlencodedBody() {
    return bodyCase_ == 11;
  }
  /**
   * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
   * @return The httpFormUrlencodedBody.
   */
  @java.lang.Override
  public org.aware.model.HttpFormUrlencodedBody getHttpFormUrlencodedBody() {
    if (bodyCase_ == 11) {
       return (org.aware.model.HttpFormUrlencodedBody) body_;
    }
    return org.aware.model.HttpFormUrlencodedBody.getDefaultInstance();
  }
  /**
   * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
   */
  @java.lang.Override
  public org.aware.model.HttpFormUrlencodedBodyOrBuilder getHttpFormUrlencodedBodyOrBuilder() {
    if (bodyCase_ == 11) {
       return (org.aware.model.HttpFormUrlencodedBody) body_;
    }
    return org.aware.model.HttpFormUrlencodedBody.getDefaultInstance();
  }

  public static final int BINARY_DATA_BODY_FIELD_NUMBER = 9;
  /**
   * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
   * @return Whether the binaryDataBody field is set.
   */
  @java.lang.Override
  public boolean hasBinaryDataBody() {
    return bodyCase_ == 9;
  }
  /**
   * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
   * @return The binaryDataBody.
   */
  @java.lang.Override
  public org.aware.model.BinaryDataBody getBinaryDataBody() {
    if (bodyCase_ == 9) {
       return (org.aware.model.BinaryDataBody) body_;
    }
    return org.aware.model.BinaryDataBody.getDefaultInstance();
  }
  /**
   * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
   */
  @java.lang.Override
  public org.aware.model.BinaryDataBodyOrBuilder getBinaryDataBodyOrBuilder() {
    if (bodyCase_ == 9) {
       return (org.aware.model.BinaryDataBody) body_;
    }
    return org.aware.model.BinaryDataBody.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetHeaderMap(),
        HeaderMapDefaultEntryHolder.defaultEntry,
        1);
    if (bodyCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, body_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, httpMethod_);
    }
    if (bodyCase_ == 4) {
      output.writeMessage(4, (org.aware.model.HttpGetBody) body_);
    }
    if (bodyCase_ == 5) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, body_);
    }
    if (bodyCase_ == 6) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, body_);
    }
    if (bodyCase_ == 7) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, body_);
    }
    if (bodyCase_ == 8) {
      output.writeMessage(8, (org.aware.model.HttpFormDataBody) body_);
    }
    if (bodyCase_ == 9) {
      output.writeMessage(9, (org.aware.model.BinaryDataBody) body_);
    }
    if (bodyCase_ == 11) {
      output.writeMessage(11, (org.aware.model.HttpFormUrlencodedBody) body_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(12, responseCode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetHeaderMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      headerMap__ = HeaderMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, headerMap__);
    }
    if (bodyCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, body_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, httpMethod_);
    }
    if (bodyCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (org.aware.model.HttpGetBody) body_);
    }
    if (bodyCase_ == 5) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, body_);
    }
    if (bodyCase_ == 6) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, body_);
    }
    if (bodyCase_ == 7) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, body_);
    }
    if (bodyCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (org.aware.model.HttpFormDataBody) body_);
    }
    if (bodyCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (org.aware.model.BinaryDataBody) body_);
    }
    if (bodyCase_ == 11) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, (org.aware.model.HttpFormUrlencodedBody) body_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, responseCode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.aware.model.HttpPayload)) {
      return super.equals(obj);
    }
    org.aware.model.HttpPayload other = (org.aware.model.HttpPayload) obj;

    if (!internalGetHeaderMap().equals(
        other.internalGetHeaderMap())) return false;
    if (hasHttpMethod() != other.hasHttpMethod()) return false;
    if (hasHttpMethod()) {
      if (!getHttpMethod()
          .equals(other.getHttpMethod())) return false;
    }
    if (hasResponseCode() != other.hasResponseCode()) return false;
    if (hasResponseCode()) {
      if (getResponseCode()
          != other.getResponseCode()) return false;
    }
    if (!getBodyCase().equals(other.getBodyCase())) return false;
    switch (bodyCase_) {
      case 2:
        if (!getJsonBody()
            .equals(other.getJsonBody())) return false;
        break;
      case 4:
        if (!getHttpGetBody()
            .equals(other.getHttpGetBody())) return false;
        break;
      case 5:
        if (!getTextBody()
            .equals(other.getTextBody())) return false;
        break;
      case 6:
        if (!getHtmlBody()
            .equals(other.getHtmlBody())) return false;
        break;
      case 7:
        if (!getXmlBody()
            .equals(other.getXmlBody())) return false;
        break;
      case 8:
        if (!getHttpFormDataBody()
            .equals(other.getHttpFormDataBody())) return false;
        break;
      case 11:
        if (!getHttpFormUrlencodedBody()
            .equals(other.getHttpFormUrlencodedBody())) return false;
        break;
      case 9:
        if (!getBinaryDataBody()
            .equals(other.getBinaryDataBody())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetHeaderMap().getMap().isEmpty()) {
      hash = (37 * hash) + HEADER_MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetHeaderMap().hashCode();
    }
    if (hasHttpMethod()) {
      hash = (37 * hash) + HTTP_METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getHttpMethod().hashCode();
    }
    if (hasResponseCode()) {
      hash = (37 * hash) + RESPONSE_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
    }
    switch (bodyCase_) {
      case 2:
        hash = (37 * hash) + JSON_BODY_FIELD_NUMBER;
        hash = (53 * hash) + getJsonBody().hashCode();
        break;
      case 4:
        hash = (37 * hash) + HTTP_GET_BODY_FIELD_NUMBER;
        hash = (53 * hash) + getHttpGetBody().hashCode();
        break;
      case 5:
        hash = (37 * hash) + TEXT_BODY_FIELD_NUMBER;
        hash = (53 * hash) + getTextBody().hashCode();
        break;
      case 6:
        hash = (37 * hash) + HTML_BODY_FIELD_NUMBER;
        hash = (53 * hash) + getHtmlBody().hashCode();
        break;
      case 7:
        hash = (37 * hash) + XML_BODY_FIELD_NUMBER;
        hash = (53 * hash) + getXmlBody().hashCode();
        break;
      case 8:
        hash = (37 * hash) + HTTP_FORM_DATA_BODY_FIELD_NUMBER;
        hash = (53 * hash) + getHttpFormDataBody().hashCode();
        break;
      case 11:
        hash = (37 * hash) + HTTP_FORM_URLENCODED_BODY_FIELD_NUMBER;
        hash = (53 * hash) + getHttpFormUrlencodedBody().hashCode();
        break;
      case 9:
        hash = (37 * hash) + BINARY_DATA_BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBinaryDataBody().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.aware.model.HttpPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.aware.model.HttpPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.aware.model.HttpPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.aware.model.HttpPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.aware.model.HttpPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.aware.model.HttpPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.aware.model.HttpPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.aware.model.HttpPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.aware.model.HttpPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.aware.model.HttpPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.aware.model.HttpPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.aware.model.HttpPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.aware.model.HttpPayload prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Represents an arbitrary http(s) payload of requests / responses.
   * </pre>
   *
   * Protobuf type {@code org.aware.model.HttpPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.aware.model.HttpPayload)
      org.aware.model.HttpPayloadOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.aware.model.Model.internal_static_org_aware_model_HttpPayload_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetHeaderMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableHeaderMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.aware.model.Model.internal_static_org_aware_model_HttpPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.aware.model.HttpPayload.class, org.aware.model.HttpPayload.Builder.class);
    }

    // Construct using org.aware.model.HttpPayload.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableHeaderMap().clear();
      httpMethod_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      responseCode_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (httpGetBodyBuilder_ != null) {
        httpGetBodyBuilder_.clear();
      }
      if (httpFormDataBodyBuilder_ != null) {
        httpFormDataBodyBuilder_.clear();
      }
      if (httpFormUrlencodedBodyBuilder_ != null) {
        httpFormUrlencodedBodyBuilder_.clear();
      }
      if (binaryDataBodyBuilder_ != null) {
        binaryDataBodyBuilder_.clear();
      }
      bodyCase_ = 0;
      body_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.aware.model.Model.internal_static_org_aware_model_HttpPayload_descriptor;
    }

    @java.lang.Override
    public org.aware.model.HttpPayload getDefaultInstanceForType() {
      return org.aware.model.HttpPayload.getDefaultInstance();
    }

    @java.lang.Override
    public org.aware.model.HttpPayload build() {
      org.aware.model.HttpPayload result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.aware.model.HttpPayload buildPartial() {
      org.aware.model.HttpPayload result = new org.aware.model.HttpPayload(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.headerMap_ = internalGetHeaderMap();
      result.headerMap_.makeImmutable();
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.httpMethod_ = httpMethod_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.responseCode_ = responseCode_;
        to_bitField0_ |= 0x00000002;
      }
      if (bodyCase_ == 2) {
        result.body_ = body_;
      }
      if (bodyCase_ == 4) {
        if (httpGetBodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = httpGetBodyBuilder_.build();
        }
      }
      if (bodyCase_ == 5) {
        result.body_ = body_;
      }
      if (bodyCase_ == 6) {
        result.body_ = body_;
      }
      if (bodyCase_ == 7) {
        result.body_ = body_;
      }
      if (bodyCase_ == 8) {
        if (httpFormDataBodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = httpFormDataBodyBuilder_.build();
        }
      }
      if (bodyCase_ == 11) {
        if (httpFormUrlencodedBodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = httpFormUrlencodedBodyBuilder_.build();
        }
      }
      if (bodyCase_ == 9) {
        if (binaryDataBodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = binaryDataBodyBuilder_.build();
        }
      }
      result.bitField0_ = to_bitField0_;
      result.bodyCase_ = bodyCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.aware.model.HttpPayload) {
        return mergeFrom((org.aware.model.HttpPayload)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.aware.model.HttpPayload other) {
      if (other == org.aware.model.HttpPayload.getDefaultInstance()) return this;
      internalGetMutableHeaderMap().mergeFrom(
          other.internalGetHeaderMap());
      if (other.hasHttpMethod()) {
        bitField0_ |= 0x00000002;
        httpMethod_ = other.httpMethod_;
        onChanged();
      }
      if (other.hasResponseCode()) {
        setResponseCode(other.getResponseCode());
      }
      switch (other.getBodyCase()) {
        case JSON_BODY: {
          bodyCase_ = 2;
          body_ = other.body_;
          onChanged();
          break;
        }
        case HTTP_GET_BODY: {
          mergeHttpGetBody(other.getHttpGetBody());
          break;
        }
        case TEXT_BODY: {
          bodyCase_ = 5;
          body_ = other.body_;
          onChanged();
          break;
        }
        case HTML_BODY: {
          bodyCase_ = 6;
          body_ = other.body_;
          onChanged();
          break;
        }
        case XML_BODY: {
          bodyCase_ = 7;
          body_ = other.body_;
          onChanged();
          break;
        }
        case HTTP_FORM_DATA_BODY: {
          mergeHttpFormDataBody(other.getHttpFormDataBody());
          break;
        }
        case HTTP_FORM_URLENCODED_BODY: {
          mergeHttpFormUrlencodedBody(other.getHttpFormUrlencodedBody());
          break;
        }
        case BINARY_DATA_BODY: {
          mergeBinaryDataBody(other.getBinaryDataBody());
          break;
        }
        case BODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              headerMap__ = input.readMessage(
                  HeaderMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableHeaderMap().getMutableMap().put(
                  headerMap__.getKey(), headerMap__.getValue());
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              bodyCase_ = 2;
              body_ = s;
              break;
            } // case 18
            case 26: {
              httpMethod_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getHttpGetBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 4;
              break;
            } // case 34
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              bodyCase_ = 5;
              body_ = s;
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              bodyCase_ = 6;
              body_ = s;
              break;
            } // case 50
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              bodyCase_ = 7;
              body_ = s;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getHttpFormDataBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 8;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getBinaryDataBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 9;
              break;
            } // case 74
            case 90: {
              input.readMessage(
                  getHttpFormUrlencodedBodyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 11;
              break;
            } // case 90
            case 96: {
              responseCode_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 96
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public BodyCase
        getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public Builder clearBody() {
      bodyCase_ = 0;
      body_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> headerMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetHeaderMap() {
      if (headerMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HeaderMapDefaultEntryHolder.defaultEntry);
      }
      return headerMap_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableHeaderMap() {
      onChanged();;
      if (headerMap_ == null) {
        headerMap_ = com.google.protobuf.MapField.newMapField(
            HeaderMapDefaultEntryHolder.defaultEntry);
      }
      if (!headerMap_.isMutable()) {
        headerMap_ = headerMap_.copy();
      }
      return headerMap_;
    }

    public int getHeaderMapCount() {
      return internalGetHeaderMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; header_map = 1;</code>
     */

    @java.lang.Override
    public boolean containsHeaderMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetHeaderMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHeaderMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getHeaderMap() {
      return getHeaderMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; header_map = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getHeaderMapMap() {
      return internalGetHeaderMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; header_map = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getHeaderMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaderMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; header_map = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getHeaderMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaderMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearHeaderMap() {
      internalGetMutableHeaderMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; header_map = 1;</code>
     */

    public Builder removeHeaderMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableHeaderMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableHeaderMap() {
      return internalGetMutableHeaderMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; header_map = 1;</code>
     */
    public Builder putHeaderMap(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableHeaderMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; header_map = 1;</code>
     */

    public Builder putAllHeaderMap(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableHeaderMap().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.lang.Object httpMethod_ = "";
    /**
     * <pre>
     * Only applicable for request payloads.
     * </pre>
     *
     * <code>optional string http_method = 3;</code>
     * @return Whether the httpMethod field is set.
     */
    public boolean hasHttpMethod() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Only applicable for request payloads.
     * </pre>
     *
     * <code>optional string http_method = 3;</code>
     * @return The httpMethod.
     */
    public java.lang.String getHttpMethod() {
      java.lang.Object ref = httpMethod_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        httpMethod_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Only applicable for request payloads.
     * </pre>
     *
     * <code>optional string http_method = 3;</code>
     * @return The bytes for httpMethod.
     */
    public com.google.protobuf.ByteString
        getHttpMethodBytes() {
      java.lang.Object ref = httpMethod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        httpMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Only applicable for request payloads.
     * </pre>
     *
     * <code>optional string http_method = 3;</code>
     * @param value The httpMethod to set.
     * @return This builder for chaining.
     */
    public Builder setHttpMethod(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      httpMethod_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Only applicable for request payloads.
     * </pre>
     *
     * <code>optional string http_method = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearHttpMethod() {
      bitField0_ = (bitField0_ & ~0x00000002);
      httpMethod_ = getDefaultInstance().getHttpMethod();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Only applicable for request payloads.
     * </pre>
     *
     * <code>optional string http_method = 3;</code>
     * @param value The bytes for httpMethod to set.
     * @return This builder for chaining.
     */
    public Builder setHttpMethodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      httpMethod_ = value;
      onChanged();
      return this;
    }

    private int responseCode_ ;
    /**
     * <pre>
     * Only applicable for response payloads.
     * </pre>
     *
     * <code>optional int32 response_code = 12;</code>
     * @return Whether the responseCode field is set.
     */
    @java.lang.Override
    public boolean hasResponseCode() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Only applicable for response payloads.
     * </pre>
     *
     * <code>optional int32 response_code = 12;</code>
     * @return The responseCode.
     */
    @java.lang.Override
    public int getResponseCode() {
      return responseCode_;
    }
    /**
     * <pre>
     * Only applicable for response payloads.
     * </pre>
     *
     * <code>optional int32 response_code = 12;</code>
     * @param value The responseCode to set.
     * @return This builder for chaining.
     */
    public Builder setResponseCode(int value) {
      bitField0_ |= 0x00000004;
      responseCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Only applicable for response payloads.
     * </pre>
     *
     * <code>optional int32 response_code = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseCode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      responseCode_ = 0;
      onChanged();
      return this;
    }

    /**
     * <code>string json_body = 2;</code>
     * @return Whether the jsonBody field is set.
     */
    @java.lang.Override
    public boolean hasJsonBody() {
      return bodyCase_ == 2;
    }
    /**
     * <code>string json_body = 2;</code>
     * @return The jsonBody.
     */
    @java.lang.Override
    public java.lang.String getJsonBody() {
      java.lang.Object ref = "";
      if (bodyCase_ == 2) {
        ref = body_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bodyCase_ == 2) {
          body_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string json_body = 2;</code>
     * @return The bytes for jsonBody.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJsonBodyBytes() {
      java.lang.Object ref = "";
      if (bodyCase_ == 2) {
        ref = body_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (bodyCase_ == 2) {
          body_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string json_body = 2;</code>
     * @param value The jsonBody to set.
     * @return This builder for chaining.
     */
    public Builder setJsonBody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 2;
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string json_body = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearJsonBody() {
      if (bodyCase_ == 2) {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string json_body = 2;</code>
     * @param value The bytes for jsonBody to set.
     * @return This builder for chaining.
     */
    public Builder setJsonBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bodyCase_ = 2;
      body_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.aware.model.HttpGetBody, org.aware.model.HttpGetBody.Builder, org.aware.model.HttpGetBodyOrBuilder> httpGetBodyBuilder_;
    /**
     * <code>.org.aware.model.HttpGetBody http_get_body = 4;</code>
     * @return Whether the httpGetBody field is set.
     */
    @java.lang.Override
    public boolean hasHttpGetBody() {
      return bodyCase_ == 4;
    }
    /**
     * <code>.org.aware.model.HttpGetBody http_get_body = 4;</code>
     * @return The httpGetBody.
     */
    @java.lang.Override
    public org.aware.model.HttpGetBody getHttpGetBody() {
      if (httpGetBodyBuilder_ == null) {
        if (bodyCase_ == 4) {
          return (org.aware.model.HttpGetBody) body_;
        }
        return org.aware.model.HttpGetBody.getDefaultInstance();
      } else {
        if (bodyCase_ == 4) {
          return httpGetBodyBuilder_.getMessage();
        }
        return org.aware.model.HttpGetBody.getDefaultInstance();
      }
    }
    /**
     * <code>.org.aware.model.HttpGetBody http_get_body = 4;</code>
     */
    public Builder setHttpGetBody(org.aware.model.HttpGetBody value) {
      if (httpGetBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        httpGetBodyBuilder_.setMessage(value);
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.org.aware.model.HttpGetBody http_get_body = 4;</code>
     */
    public Builder setHttpGetBody(
        org.aware.model.HttpGetBody.Builder builderForValue) {
      if (httpGetBodyBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        httpGetBodyBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.org.aware.model.HttpGetBody http_get_body = 4;</code>
     */
    public Builder mergeHttpGetBody(org.aware.model.HttpGetBody value) {
      if (httpGetBodyBuilder_ == null) {
        if (bodyCase_ == 4 &&
            body_ != org.aware.model.HttpGetBody.getDefaultInstance()) {
          body_ = org.aware.model.HttpGetBody.newBuilder((org.aware.model.HttpGetBody) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 4) {
          httpGetBodyBuilder_.mergeFrom(value);
        } else {
          httpGetBodyBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.org.aware.model.HttpGetBody http_get_body = 4;</code>
     */
    public Builder clearHttpGetBody() {
      if (httpGetBodyBuilder_ == null) {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
        }
        httpGetBodyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.org.aware.model.HttpGetBody http_get_body = 4;</code>
     */
    public org.aware.model.HttpGetBody.Builder getHttpGetBodyBuilder() {
      return getHttpGetBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.aware.model.HttpGetBody http_get_body = 4;</code>
     */
    @java.lang.Override
    public org.aware.model.HttpGetBodyOrBuilder getHttpGetBodyOrBuilder() {
      if ((bodyCase_ == 4) && (httpGetBodyBuilder_ != null)) {
        return httpGetBodyBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 4) {
          return (org.aware.model.HttpGetBody) body_;
        }
        return org.aware.model.HttpGetBody.getDefaultInstance();
      }
    }
    /**
     * <code>.org.aware.model.HttpGetBody http_get_body = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.aware.model.HttpGetBody, org.aware.model.HttpGetBody.Builder, org.aware.model.HttpGetBodyOrBuilder> 
        getHttpGetBodyFieldBuilder() {
      if (httpGetBodyBuilder_ == null) {
        if (!(bodyCase_ == 4)) {
          body_ = org.aware.model.HttpGetBody.getDefaultInstance();
        }
        httpGetBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.aware.model.HttpGetBody, org.aware.model.HttpGetBody.Builder, org.aware.model.HttpGetBodyOrBuilder>(
                (org.aware.model.HttpGetBody) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 4;
      onChanged();;
      return httpGetBodyBuilder_;
    }

    /**
     * <code>string text_body = 5;</code>
     * @return Whether the textBody field is set.
     */
    @java.lang.Override
    public boolean hasTextBody() {
      return bodyCase_ == 5;
    }
    /**
     * <code>string text_body = 5;</code>
     * @return The textBody.
     */
    @java.lang.Override
    public java.lang.String getTextBody() {
      java.lang.Object ref = "";
      if (bodyCase_ == 5) {
        ref = body_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bodyCase_ == 5) {
          body_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string text_body = 5;</code>
     * @return The bytes for textBody.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBodyBytes() {
      java.lang.Object ref = "";
      if (bodyCase_ == 5) {
        ref = body_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (bodyCase_ == 5) {
          body_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string text_body = 5;</code>
     * @param value The textBody to set.
     * @return This builder for chaining.
     */
    public Builder setTextBody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 5;
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string text_body = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTextBody() {
      if (bodyCase_ == 5) {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string text_body = 5;</code>
     * @param value The bytes for textBody to set.
     * @return This builder for chaining.
     */
    public Builder setTextBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bodyCase_ = 5;
      body_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string html_body = 6;</code>
     * @return Whether the htmlBody field is set.
     */
    @java.lang.Override
    public boolean hasHtmlBody() {
      return bodyCase_ == 6;
    }
    /**
     * <code>string html_body = 6;</code>
     * @return The htmlBody.
     */
    @java.lang.Override
    public java.lang.String getHtmlBody() {
      java.lang.Object ref = "";
      if (bodyCase_ == 6) {
        ref = body_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bodyCase_ == 6) {
          body_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string html_body = 6;</code>
     * @return The bytes for htmlBody.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHtmlBodyBytes() {
      java.lang.Object ref = "";
      if (bodyCase_ == 6) {
        ref = body_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (bodyCase_ == 6) {
          body_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string html_body = 6;</code>
     * @param value The htmlBody to set.
     * @return This builder for chaining.
     */
    public Builder setHtmlBody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 6;
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string html_body = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearHtmlBody() {
      if (bodyCase_ == 6) {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string html_body = 6;</code>
     * @param value The bytes for htmlBody to set.
     * @return This builder for chaining.
     */
    public Builder setHtmlBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bodyCase_ = 6;
      body_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string xml_body = 7;</code>
     * @return Whether the xmlBody field is set.
     */
    @java.lang.Override
    public boolean hasXmlBody() {
      return bodyCase_ == 7;
    }
    /**
     * <code>string xml_body = 7;</code>
     * @return The xmlBody.
     */
    @java.lang.Override
    public java.lang.String getXmlBody() {
      java.lang.Object ref = "";
      if (bodyCase_ == 7) {
        ref = body_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bodyCase_ == 7) {
          body_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string xml_body = 7;</code>
     * @return The bytes for xmlBody.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getXmlBodyBytes() {
      java.lang.Object ref = "";
      if (bodyCase_ == 7) {
        ref = body_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (bodyCase_ == 7) {
          body_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string xml_body = 7;</code>
     * @param value The xmlBody to set.
     * @return This builder for chaining.
     */
    public Builder setXmlBody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bodyCase_ = 7;
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string xml_body = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearXmlBody() {
      if (bodyCase_ == 7) {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string xml_body = 7;</code>
     * @param value The bytes for xmlBody to set.
     * @return This builder for chaining.
     */
    public Builder setXmlBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bodyCase_ = 7;
      body_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.aware.model.HttpFormDataBody, org.aware.model.HttpFormDataBody.Builder, org.aware.model.HttpFormDataBodyOrBuilder> httpFormDataBodyBuilder_;
    /**
     * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
     * @return Whether the httpFormDataBody field is set.
     */
    @java.lang.Override
    public boolean hasHttpFormDataBody() {
      return bodyCase_ == 8;
    }
    /**
     * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
     * @return The httpFormDataBody.
     */
    @java.lang.Override
    public org.aware.model.HttpFormDataBody getHttpFormDataBody() {
      if (httpFormDataBodyBuilder_ == null) {
        if (bodyCase_ == 8) {
          return (org.aware.model.HttpFormDataBody) body_;
        }
        return org.aware.model.HttpFormDataBody.getDefaultInstance();
      } else {
        if (bodyCase_ == 8) {
          return httpFormDataBodyBuilder_.getMessage();
        }
        return org.aware.model.HttpFormDataBody.getDefaultInstance();
      }
    }
    /**
     * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
     */
    public Builder setHttpFormDataBody(org.aware.model.HttpFormDataBody value) {
      if (httpFormDataBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        httpFormDataBodyBuilder_.setMessage(value);
      }
      bodyCase_ = 8;
      return this;
    }
    /**
     * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
     */
    public Builder setHttpFormDataBody(
        org.aware.model.HttpFormDataBody.Builder builderForValue) {
      if (httpFormDataBodyBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        httpFormDataBodyBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 8;
      return this;
    }
    /**
     * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
     */
    public Builder mergeHttpFormDataBody(org.aware.model.HttpFormDataBody value) {
      if (httpFormDataBodyBuilder_ == null) {
        if (bodyCase_ == 8 &&
            body_ != org.aware.model.HttpFormDataBody.getDefaultInstance()) {
          body_ = org.aware.model.HttpFormDataBody.newBuilder((org.aware.model.HttpFormDataBody) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 8) {
          httpFormDataBodyBuilder_.mergeFrom(value);
        } else {
          httpFormDataBodyBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 8;
      return this;
    }
    /**
     * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
     */
    public Builder clearHttpFormDataBody() {
      if (httpFormDataBodyBuilder_ == null) {
        if (bodyCase_ == 8) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 8) {
          bodyCase_ = 0;
          body_ = null;
        }
        httpFormDataBodyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
     */
    public org.aware.model.HttpFormDataBody.Builder getHttpFormDataBodyBuilder() {
      return getHttpFormDataBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
     */
    @java.lang.Override
    public org.aware.model.HttpFormDataBodyOrBuilder getHttpFormDataBodyOrBuilder() {
      if ((bodyCase_ == 8) && (httpFormDataBodyBuilder_ != null)) {
        return httpFormDataBodyBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 8) {
          return (org.aware.model.HttpFormDataBody) body_;
        }
        return org.aware.model.HttpFormDataBody.getDefaultInstance();
      }
    }
    /**
     * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.aware.model.HttpFormDataBody, org.aware.model.HttpFormDataBody.Builder, org.aware.model.HttpFormDataBodyOrBuilder> 
        getHttpFormDataBodyFieldBuilder() {
      if (httpFormDataBodyBuilder_ == null) {
        if (!(bodyCase_ == 8)) {
          body_ = org.aware.model.HttpFormDataBody.getDefaultInstance();
        }
        httpFormDataBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.aware.model.HttpFormDataBody, org.aware.model.HttpFormDataBody.Builder, org.aware.model.HttpFormDataBodyOrBuilder>(
                (org.aware.model.HttpFormDataBody) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 8;
      onChanged();;
      return httpFormDataBodyBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.aware.model.HttpFormUrlencodedBody, org.aware.model.HttpFormUrlencodedBody.Builder, org.aware.model.HttpFormUrlencodedBodyOrBuilder> httpFormUrlencodedBodyBuilder_;
    /**
     * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
     * @return Whether the httpFormUrlencodedBody field is set.
     */
    @java.lang.Override
    public boolean hasHttpFormUrlencodedBody() {
      return bodyCase_ == 11;
    }
    /**
     * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
     * @return The httpFormUrlencodedBody.
     */
    @java.lang.Override
    public org.aware.model.HttpFormUrlencodedBody getHttpFormUrlencodedBody() {
      if (httpFormUrlencodedBodyBuilder_ == null) {
        if (bodyCase_ == 11) {
          return (org.aware.model.HttpFormUrlencodedBody) body_;
        }
        return org.aware.model.HttpFormUrlencodedBody.getDefaultInstance();
      } else {
        if (bodyCase_ == 11) {
          return httpFormUrlencodedBodyBuilder_.getMessage();
        }
        return org.aware.model.HttpFormUrlencodedBody.getDefaultInstance();
      }
    }
    /**
     * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
     */
    public Builder setHttpFormUrlencodedBody(org.aware.model.HttpFormUrlencodedBody value) {
      if (httpFormUrlencodedBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        httpFormUrlencodedBodyBuilder_.setMessage(value);
      }
      bodyCase_ = 11;
      return this;
    }
    /**
     * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
     */
    public Builder setHttpFormUrlencodedBody(
        org.aware.model.HttpFormUrlencodedBody.Builder builderForValue) {
      if (httpFormUrlencodedBodyBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        httpFormUrlencodedBodyBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 11;
      return this;
    }
    /**
     * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
     */
    public Builder mergeHttpFormUrlencodedBody(org.aware.model.HttpFormUrlencodedBody value) {
      if (httpFormUrlencodedBodyBuilder_ == null) {
        if (bodyCase_ == 11 &&
            body_ != org.aware.model.HttpFormUrlencodedBody.getDefaultInstance()) {
          body_ = org.aware.model.HttpFormUrlencodedBody.newBuilder((org.aware.model.HttpFormUrlencodedBody) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 11) {
          httpFormUrlencodedBodyBuilder_.mergeFrom(value);
        } else {
          httpFormUrlencodedBodyBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 11;
      return this;
    }
    /**
     * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
     */
    public Builder clearHttpFormUrlencodedBody() {
      if (httpFormUrlencodedBodyBuilder_ == null) {
        if (bodyCase_ == 11) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 11) {
          bodyCase_ = 0;
          body_ = null;
        }
        httpFormUrlencodedBodyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
     */
    public org.aware.model.HttpFormUrlencodedBody.Builder getHttpFormUrlencodedBodyBuilder() {
      return getHttpFormUrlencodedBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
     */
    @java.lang.Override
    public org.aware.model.HttpFormUrlencodedBodyOrBuilder getHttpFormUrlencodedBodyOrBuilder() {
      if ((bodyCase_ == 11) && (httpFormUrlencodedBodyBuilder_ != null)) {
        return httpFormUrlencodedBodyBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 11) {
          return (org.aware.model.HttpFormUrlencodedBody) body_;
        }
        return org.aware.model.HttpFormUrlencodedBody.getDefaultInstance();
      }
    }
    /**
     * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.aware.model.HttpFormUrlencodedBody, org.aware.model.HttpFormUrlencodedBody.Builder, org.aware.model.HttpFormUrlencodedBodyOrBuilder> 
        getHttpFormUrlencodedBodyFieldBuilder() {
      if (httpFormUrlencodedBodyBuilder_ == null) {
        if (!(bodyCase_ == 11)) {
          body_ = org.aware.model.HttpFormUrlencodedBody.getDefaultInstance();
        }
        httpFormUrlencodedBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.aware.model.HttpFormUrlencodedBody, org.aware.model.HttpFormUrlencodedBody.Builder, org.aware.model.HttpFormUrlencodedBodyOrBuilder>(
                (org.aware.model.HttpFormUrlencodedBody) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 11;
      onChanged();;
      return httpFormUrlencodedBodyBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.aware.model.BinaryDataBody, org.aware.model.BinaryDataBody.Builder, org.aware.model.BinaryDataBodyOrBuilder> binaryDataBodyBuilder_;
    /**
     * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
     * @return Whether the binaryDataBody field is set.
     */
    @java.lang.Override
    public boolean hasBinaryDataBody() {
      return bodyCase_ == 9;
    }
    /**
     * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
     * @return The binaryDataBody.
     */
    @java.lang.Override
    public org.aware.model.BinaryDataBody getBinaryDataBody() {
      if (binaryDataBodyBuilder_ == null) {
        if (bodyCase_ == 9) {
          return (org.aware.model.BinaryDataBody) body_;
        }
        return org.aware.model.BinaryDataBody.getDefaultInstance();
      } else {
        if (bodyCase_ == 9) {
          return binaryDataBodyBuilder_.getMessage();
        }
        return org.aware.model.BinaryDataBody.getDefaultInstance();
      }
    }
    /**
     * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
     */
    public Builder setBinaryDataBody(org.aware.model.BinaryDataBody value) {
      if (binaryDataBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        binaryDataBodyBuilder_.setMessage(value);
      }
      bodyCase_ = 9;
      return this;
    }
    /**
     * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
     */
    public Builder setBinaryDataBody(
        org.aware.model.BinaryDataBody.Builder builderForValue) {
      if (binaryDataBodyBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        binaryDataBodyBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 9;
      return this;
    }
    /**
     * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
     */
    public Builder mergeBinaryDataBody(org.aware.model.BinaryDataBody value) {
      if (binaryDataBodyBuilder_ == null) {
        if (bodyCase_ == 9 &&
            body_ != org.aware.model.BinaryDataBody.getDefaultInstance()) {
          body_ = org.aware.model.BinaryDataBody.newBuilder((org.aware.model.BinaryDataBody) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 9) {
          binaryDataBodyBuilder_.mergeFrom(value);
        } else {
          binaryDataBodyBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 9;
      return this;
    }
    /**
     * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
     */
    public Builder clearBinaryDataBody() {
      if (binaryDataBodyBuilder_ == null) {
        if (bodyCase_ == 9) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 9) {
          bodyCase_ = 0;
          body_ = null;
        }
        binaryDataBodyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
     */
    public org.aware.model.BinaryDataBody.Builder getBinaryDataBodyBuilder() {
      return getBinaryDataBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
     */
    @java.lang.Override
    public org.aware.model.BinaryDataBodyOrBuilder getBinaryDataBodyOrBuilder() {
      if ((bodyCase_ == 9) && (binaryDataBodyBuilder_ != null)) {
        return binaryDataBodyBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 9) {
          return (org.aware.model.BinaryDataBody) body_;
        }
        return org.aware.model.BinaryDataBody.getDefaultInstance();
      }
    }
    /**
     * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.aware.model.BinaryDataBody, org.aware.model.BinaryDataBody.Builder, org.aware.model.BinaryDataBodyOrBuilder> 
        getBinaryDataBodyFieldBuilder() {
      if (binaryDataBodyBuilder_ == null) {
        if (!(bodyCase_ == 9)) {
          body_ = org.aware.model.BinaryDataBody.getDefaultInstance();
        }
        binaryDataBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.aware.model.BinaryDataBody, org.aware.model.BinaryDataBody.Builder, org.aware.model.BinaryDataBodyOrBuilder>(
                (org.aware.model.BinaryDataBody) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 9;
      onChanged();;
      return binaryDataBodyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.aware.model.HttpPayload)
  }

  // @@protoc_insertion_point(class_scope:org.aware.model.HttpPayload)
  private static final org.aware.model.HttpPayload DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.aware.model.HttpPayload();
  }

  public static org.aware.model.HttpPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HttpPayload>
      PARSER = new com.google.protobuf.AbstractParser<HttpPayload>() {
    @java.lang.Override
    public HttpPayload parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HttpPayload> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HttpPayload> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.aware.model.HttpPayload getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

