// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.aware.model;

public interface HttpFormUrlencodedBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.aware.model.HttpFormUrlencodedBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; key_value_map = 1;</code>
   */
  int getKeyValueMapCount();
  /**
   * <code>map&lt;string, string&gt; key_value_map = 1;</code> force
   */
  boolean containsKeyValueMap(
      java.lang.String key);
  /**
   * Use {@link #getKeyValueMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getKeyValueMap();
  /**
   * <code>map&lt;string, string&gt; key_value_map = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getKeyValueMapMap();
  /**
   * <code>map&lt;string, string&gt; key_value_map = 1;</code>
   */

  /* nullable */
java.lang.String getKeyValueMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; key_value_map = 1;</code>
   */

  java.lang.String getKeyValueMapOrThrow(
      java.lang.String key);
}
