// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.aware.model;

/**
 * Protobuf type {@code org.aware.model.HttpFormUrlencodedBody} force
 */
public final class HttpFormUrlencodedBody extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.aware.model.HttpFormUrlencodedBody)
    HttpFormUrlencodedBodyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HttpFormUrlencodedBody.newBuilder() to construct.
  private HttpFormUrlencodedBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HttpFormUrlencodedBody() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HttpFormUrlencodedBody();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.aware.model.Model.internal_static_org_aware_model_HttpFormUrlencodedBody_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetKeyValueMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.aware.model.Model.internal_static_org_aware_model_HttpFormUrlencodedBody_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.aware.model.HttpFormUrlencodedBody.class, org.aware.model.HttpFormUrlencodedBody.Builder.class);
  }

  public static final int KEY_VALUE_MAP_FIELD_NUMBER = 1;
  private static final class KeyValueMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                org.aware.model.Model.internal_static_org_aware_model_HttpFormUrlencodedBody_KeyValueMapEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> keyValueMap_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetKeyValueMap() {
    if (keyValueMap_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          KeyValueMapDefaultEntryHolder.defaultEntry);
    }
    return keyValueMap_;
  }

  public int getKeyValueMapCount() {
    return internalGetKeyValueMap().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; key_value_map = 1;</code>
   */

  @java.lang.Override
  public boolean containsKeyValueMap(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetKeyValueMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getKeyValueMapMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getKeyValueMap() {
    return getKeyValueMapMap();
  }
  /**
   * <code>map&lt;string, string&gt; key_value_map = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getKeyValueMapMap() {
    return internalGetKeyValueMap().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; key_value_map = 1;</code>
   */
  @java.lang.Override

  public java.lang.String getKeyValueMapOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetKeyValueMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; key_value_map = 1;</code>
   */
  @java.lang.Override

  public java.lang.String getKeyValueMapOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetKeyValueMap().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetKeyValueMap(),
        KeyValueMapDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetKeyValueMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      keyValueMap__ = KeyValueMapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, keyValueMap__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.aware.model.HttpFormUrlencodedBody)) {
      return super.equals(obj);
    }
    org.aware.model.HttpFormUrlencodedBody other = (org.aware.model.HttpFormUrlencodedBody) obj;

    if (!internalGetKeyValueMap().equals(
        other.internalGetKeyValueMap())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetKeyValueMap().getMap().isEmpty()) {
      hash = (37 * hash) + KEY_VALUE_MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetKeyValueMap().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.aware.model.HttpFormUrlencodedBody parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.aware.model.HttpFormUrlencodedBody parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.aware.model.HttpFormUrlencodedBody parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.aware.model.HttpFormUrlencodedBody parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.aware.model.HttpFormUrlencodedBody parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.aware.model.HttpFormUrlencodedBody parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.aware.model.HttpFormUrlencodedBody parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.aware.model.HttpFormUrlencodedBody parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.aware.model.HttpFormUrlencodedBody parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.aware.model.HttpFormUrlencodedBody parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.aware.model.HttpFormUrlencodedBody parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.aware.model.HttpFormUrlencodedBody parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.aware.model.HttpFormUrlencodedBody prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.aware.model.HttpFormUrlencodedBody}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.aware.model.HttpFormUrlencodedBody)
      org.aware.model.HttpFormUrlencodedBodyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.aware.model.Model.internal_static_org_aware_model_HttpFormUrlencodedBody_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetKeyValueMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableKeyValueMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.aware.model.Model.internal_static_org_aware_model_HttpFormUrlencodedBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.aware.model.HttpFormUrlencodedBody.class, org.aware.model.HttpFormUrlencodedBody.Builder.class);
    }

    // Construct using org.aware.model.HttpFormUrlencodedBody.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableKeyValueMap().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.aware.model.Model.internal_static_org_aware_model_HttpFormUrlencodedBody_descriptor;
    }

    @java.lang.Override
    public org.aware.model.HttpFormUrlencodedBody getDefaultInstanceForType() {
      return org.aware.model.HttpFormUrlencodedBody.getDefaultInstance();
    }

    @java.lang.Override
    public org.aware.model.HttpFormUrlencodedBody build() {
      org.aware.model.HttpFormUrlencodedBody result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.aware.model.HttpFormUrlencodedBody buildPartial() {
      org.aware.model.HttpFormUrlencodedBody result = new org.aware.model.HttpFormUrlencodedBody(this);
      int from_bitField0_ = bitField0_;
      result.keyValueMap_ = internalGetKeyValueMap();
      result.keyValueMap_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.aware.model.HttpFormUrlencodedBody) {
        return mergeFrom((org.aware.model.HttpFormUrlencodedBody)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.aware.model.HttpFormUrlencodedBody other) {
      if (other == org.aware.model.HttpFormUrlencodedBody.getDefaultInstance()) return this;
      internalGetMutableKeyValueMap().mergeFrom(
          other.internalGetKeyValueMap());
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              keyValueMap__ = input.readMessage(
                  KeyValueMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableKeyValueMap().getMutableMap().put(
                  keyValueMap__.getKey(), keyValueMap__.getValue());
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> keyValueMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetKeyValueMap() {
      if (keyValueMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            KeyValueMapDefaultEntryHolder.defaultEntry);
      }
      return keyValueMap_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableKeyValueMap() {
      onChanged();;
      if (keyValueMap_ == null) {
        keyValueMap_ = com.google.protobuf.MapField.newMapField(
            KeyValueMapDefaultEntryHolder.defaultEntry);
      }
      if (!keyValueMap_.isMutable()) {
        keyValueMap_ = keyValueMap_.copy();
      }
      return keyValueMap_;
    }

    public int getKeyValueMapCount() {
      return internalGetKeyValueMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; key_value_map = 1;</code>
     */

    @java.lang.Override
    public boolean containsKeyValueMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetKeyValueMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getKeyValueMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getKeyValueMap() {
      return getKeyValueMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; key_value_map = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getKeyValueMapMap() {
      return internalGetKeyValueMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; key_value_map = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getKeyValueMapOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetKeyValueMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; key_value_map = 1;</code>
     */
    @java.lang.Override

    public java.lang.String getKeyValueMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetKeyValueMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearKeyValueMap() {
      internalGetMutableKeyValueMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; key_value_map = 1;</code>
     */

    public Builder removeKeyValueMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableKeyValueMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableKeyValueMap() {
      return internalGetMutableKeyValueMap().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; key_value_map = 1;</code>
     */
    public Builder putKeyValueMap(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableKeyValueMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; key_value_map = 1;</code>
     */

    public Builder putAllKeyValueMap(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableKeyValueMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.aware.model.HttpFormUrlencodedBody)
  }

  // @@protoc_insertion_point(class_scope:org.aware.model.HttpFormUrlencodedBody)
  private static final org.aware.model.HttpFormUrlencodedBody DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.aware.model.HttpFormUrlencodedBody();
  }

  public static org.aware.model.HttpFormUrlencodedBody getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HttpFormUrlencodedBody>
      PARSER = new com.google.protobuf.AbstractParser<HttpFormUrlencodedBody>() {
    @java.lang.Override
    public HttpFormUrlencodedBody parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HttpFormUrlencodedBody> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HttpFormUrlencodedBody> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.aware.model.HttpFormUrlencodedBody getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

