// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.aware.model;

public interface HttpPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.aware.model.HttpPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */
  int getHeaderMapCount();
  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */
  boolean containsHeaderMap(
      java.lang.String key);
  /**
   * Use {@link #getHeaderMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getHeaderMap();
  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getHeaderMapMap();
  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */

  /* nullable */
java.lang.String getHeaderMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */

  java.lang.String getHeaderMapOrThrow(
      java.lang.String key);

  /**
   * <code>map&lt;string, string&gt; query_param_map = 13;</code>
   */
  int getQueryParamMapCount();
  /**
   * <code>map&lt;string, string&gt; query_param_map = 13;</code>
   */
  boolean containsQueryParamMap(
      java.lang.String key);
  /**
   * Use {@link #getQueryParamMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getQueryParamMap();
  /**
   * <code>map&lt;string, string&gt; query_param_map = 13;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getQueryParamMapMap();
  /**
   * <code>map&lt;string, string&gt; query_param_map = 13;</code>
   */

  /* nullable */
java.lang.String getQueryParamMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; query_param_map = 13;</code>
   */

  java.lang.String getQueryParamMapOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * Only applicable for request payloads.
   * </pre>
   *
   * <code>optional string http_method = 3;</code>
   * @return Whether the httpMethod field is set.
   */
  boolean hasHttpMethod();
  /**
   * <pre>
   * Only applicable for request payloads.
   * </pre>
   *
   * <code>optional string http_method = 3;</code>
   * @return The httpMethod.
   */
  java.lang.String getHttpMethod();
  /**
   * <pre>
   * Only applicable for request payloads.
   * </pre>
   *
   * <code>optional string http_method = 3;</code>
   * @return The bytes for httpMethod.
   */
  com.google.protobuf.ByteString
      getHttpMethodBytes();

  /**
   * <pre>
   * Only applicable for response payloads.
   * </pre>
   *
   * <code>optional int32 response_code = 12;</code>
   * @return Whether the responseCode field is set.
   */
  boolean hasResponseCode();
  /**
   * <pre>
   * Only applicable for response payloads.
   * </pre>
   *
   * <code>optional int32 response_code = 12;</code>
   * @return The responseCode.
   */
  int getResponseCode();

  /**
   * <code>string json_body = 2;</code>
   * @return Whether the jsonBody field is set.
   */
  boolean hasJsonBody();
  /**
   * <code>string json_body = 2;</code>
   * @return The jsonBody.
   */
  java.lang.String getJsonBody();
  /**
   * <code>string json_body = 2;</code>
   * @return The bytes for jsonBody.
   */
  com.google.protobuf.ByteString
      getJsonBodyBytes();

  /**
   * <pre>
   * Populate query param map instead. This is since query params are not limited to GET methods.
   * </pre>
   *
   * <code>.org.aware.model.HttpGetBody http_get_body = 4 [deprecated = true];</code>
   * @deprecated org.aware.model.HttpPayload.http_get_body is deprecated.
   *     See model.proto;l=19
   * @return Whether the httpGetBody field is set.
   */
  @java.lang.Deprecated boolean hasHttpGetBody();
  /**
   * <pre>
   * Populate query param map instead. This is since query params are not limited to GET methods.
   * </pre>
   *
   * <code>.org.aware.model.HttpGetBody http_get_body = 4 [deprecated = true];</code>
   * @deprecated org.aware.model.HttpPayload.http_get_body is deprecated.
   *     See model.proto;l=19
   * @return The httpGetBody.
   */
  @java.lang.Deprecated org.aware.model.HttpGetBody getHttpGetBody();
  /**
   * <pre>
   * Populate query param map instead. This is since query params are not limited to GET methods.
   * </pre>
   *
   * <code>.org.aware.model.HttpGetBody http_get_body = 4 [deprecated = true];</code>
   */
  @java.lang.Deprecated org.aware.model.HttpGetBodyOrBuilder getHttpGetBodyOrBuilder();

  /**
   * <code>string text_body = 5;</code>
   * @return Whether the textBody field is set.
   */
  boolean hasTextBody();
  /**
   * <code>string text_body = 5;</code>
   * @return The textBody.
   */
  java.lang.String getTextBody();
  /**
   * <code>string text_body = 5;</code>
   * @return The bytes for textBody.
   */
  com.google.protobuf.ByteString
      getTextBodyBytes();

  /**
   * <code>string html_body = 6;</code>
   * @return Whether the htmlBody field is set.
   */
  boolean hasHtmlBody();
  /**
   * <code>string html_body = 6;</code>
   * @return The htmlBody.
   */
  java.lang.String getHtmlBody();
  /**
   * <code>string html_body = 6;</code>
   * @return The bytes for htmlBody.
   */
  com.google.protobuf.ByteString
      getHtmlBodyBytes();

  /**
   * <code>string xml_body = 7;</code>
   * @return Whether the xmlBody field is set.
   */
  boolean hasXmlBody();
  /**
   * <code>string xml_body = 7;</code>
   * @return The xmlBody.
   */
  java.lang.String getXmlBody();
  /**
   * <code>string xml_body = 7;</code>
   * @return The bytes for xmlBody.
   */
  com.google.protobuf.ByteString
      getXmlBodyBytes();

  /**
   * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
   * @return Whether the httpFormDataBody field is set.
   */
  boolean hasHttpFormDataBody();
  /**
   * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
   * @return The httpFormDataBody.
   */
  org.aware.model.HttpFormDataBody getHttpFormDataBody();
  /**
   * <code>.org.aware.model.HttpFormDataBody http_form_data_body = 8;</code>
   */
  org.aware.model.HttpFormDataBodyOrBuilder getHttpFormDataBodyOrBuilder();

  /**
   * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
   * @return Whether the httpFormUrlencodedBody field is set.
   */
  boolean hasHttpFormUrlencodedBody();
  /**
   * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
   * @return The httpFormUrlencodedBody.
   */
  org.aware.model.HttpFormUrlencodedBody getHttpFormUrlencodedBody();
  /**
   * <code>.org.aware.model.HttpFormUrlencodedBody http_form_urlencoded_body = 11;</code>
   */
  org.aware.model.HttpFormUrlencodedBodyOrBuilder getHttpFormUrlencodedBodyOrBuilder();

  /**
   * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
   * @return Whether the binaryDataBody field is set.
   */
  boolean hasBinaryDataBody();
  /**
   * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
   * @return The binaryDataBody.
   */
  org.aware.model.BinaryDataBody getBinaryDataBody();
  /**
   * <code>.org.aware.model.BinaryDataBody binary_data_body = 9;</code>
   */
  org.aware.model.BinaryDataBodyOrBuilder getBinaryDataBodyOrBuilder();

  public org.aware.model.HttpPayload.BodyCase getBodyCase();
}
