// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.aware.model;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_HttpPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_HttpPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_HttpPayload_HeaderMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_HttpPayload_HeaderMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_HttpGetBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_HttpGetBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_HttpGetBody_KeyValueMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_HttpGetBody_KeyValueMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_HttpFormDataBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_HttpFormDataBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_HttpFormDataBody_KeyValueMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_HttpFormDataBody_KeyValueMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_HttpFormUrlencodedBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_HttpFormUrlencodedBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_HttpFormUrlencodedBody_KeyValueMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_HttpFormUrlencodedBody_KeyValueMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_BinaryDataBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_BinaryDataBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_Payload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_Payload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_PayloadList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_PayloadList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_InsertClientRecordedPayloadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_InsertClientRecordedPayloadRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\022\017org.aware.model\"\267\004\n\013HttpP" +
      "ayload\022?\n\nheader_map\030\001 \003(\0132+.org.aware.m" +
      "odel.HttpPayload.HeaderMapEntry\022\030\n\013http_" +
      "method\030\003 \001(\tH\001\210\001\001\022\032\n\rresponse_code\030\014 \001(\005" +
      "H\002\210\001\001\022\023\n\tjson_body\030\002 \001(\tH\000\0225\n\rhttp_get_b" +
      "ody\030\004 \001(\0132\034.org.aware.model.HttpGetBodyH" +
      "\000\022\023\n\ttext_body\030\005 \001(\tH\000\022\023\n\thtml_body\030\006 \001(" +
      "\tH\000\022\022\n\010xml_body\030\007 \001(\tH\000\022@\n\023http_form_dat" +
      "a_body\030\010 \001(\0132!.org.aware.model.HttpFormD" +
      "ataBodyH\000\022L\n\031http_form_urlencoded_body\030\013" +
      " \001(\0132\'.org.aware.model.HttpFormUrlencode" +
      "dBodyH\000\022;\n\020binary_data_body\030\t \001(\0132\037.org." +
      "aware.model.BinaryDataBodyH\000\0320\n\016HeaderMa" +
      "pEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\006" +
      "\n\004bodyB\016\n\014_http_methodB\020\n\016_response_code" +
      "\"\207\001\n\013HttpGetBody\022D\n\rkey_value_map\030\001 \003(\0132" +
      "-.org.aware.model.HttpGetBody.KeyValueMa" +
      "pEntry\0322\n\020KeyValueMapEntry\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\t:\0028\001\"\221\001\n\020HttpFormDataBody\022" +
      "I\n\rkey_value_map\030\001 \003(\01322.org.aware.model" +
      ".HttpFormDataBody.KeyValueMapEntry\0322\n\020Ke" +
      "yValueMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001" +
      "(\t:\0028\001\"\235\001\n\026HttpFormUrlencodedBody\022O\n\rkey" +
      "_value_map\030\001 \003(\01328.org.aware.model.HttpF" +
      "ormUrlencodedBody.KeyValueMapEntry\0322\n\020Ke" +
      "yValueMapEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001" +
      "(\t:\0028\001\",\n\016BinaryDataBody\022\021\n\004data\030\001 \001(\014H\000" +
      "\210\001\001B\007\n\005_data\"l\n\007Payload\022\024\n\007span_id\030\001 \001(\t" +
      "H\001\210\001\001\0224\n\014http_payload\030\002 \001(\0132\034.org.aware." +
      "model.HttpPayloadH\000B\t\n\007payloadB\n\n\010_span_" +
      "id\"9\n\013PayloadList\022*\n\010payloads\030\001 \003(\0132\030.or" +
      "g.aware.model.Payload\"\330\002\n\"InsertClientRe" +
      "cordedPayloadRequest\0226\n\017request_payload\030" +
      "\001 \001(\0132\030.org.aware.model.PayloadH\000\210\001\001\0227\n\020" +
      "response_payload\030\002 \001(\0132\030.org.aware.model" +
      ".PayloadH\001\210\001\001\022\020\n\003url\030\003 \001(\tH\002\210\001\001\022*\n\035sessi" +
      "on_recording_tracking_id\030\004 \001(\tH\003\210\001\001\022\034\n\017c" +
      "urrent_user_id\030\005 \001(\tH\004\210\001\001B\022\n\020_request_pa" +
      "yloadB\023\n\021_response_payloadB\006\n\004_urlB \n\036_s" +
      "ession_recording_tracking_idB\022\n\020_current" +
      "_user_idB\032\n\017org.aware.modelB\005ModelP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_aware_model_HttpPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_aware_model_HttpPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_HttpPayload_descriptor,
        new java.lang.String[] { "HeaderMap", "HttpMethod", "ResponseCode", "JsonBody", "HttpGetBody", "TextBody", "HtmlBody", "XmlBody", "HttpFormDataBody", "HttpFormUrlencodedBody", "BinaryDataBody", "Body", "HttpMethod", "ResponseCode", });
    internal_static_org_aware_model_HttpPayload_HeaderMapEntry_descriptor =
      internal_static_org_aware_model_HttpPayload_descriptor.getNestedTypes().get(0);
    internal_static_org_aware_model_HttpPayload_HeaderMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_HttpPayload_HeaderMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_aware_model_HttpGetBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_aware_model_HttpGetBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_HttpGetBody_descriptor,
        new java.lang.String[] { "KeyValueMap", });
    internal_static_org_aware_model_HttpGetBody_KeyValueMapEntry_descriptor =
      internal_static_org_aware_model_HttpGetBody_descriptor.getNestedTypes().get(0);
    internal_static_org_aware_model_HttpGetBody_KeyValueMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_HttpGetBody_KeyValueMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_aware_model_HttpFormDataBody_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_aware_model_HttpFormDataBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_HttpFormDataBody_descriptor,
        new java.lang.String[] { "KeyValueMap", });
    internal_static_org_aware_model_HttpFormDataBody_KeyValueMapEntry_descriptor =
      internal_static_org_aware_model_HttpFormDataBody_descriptor.getNestedTypes().get(0);
    internal_static_org_aware_model_HttpFormDataBody_KeyValueMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_HttpFormDataBody_KeyValueMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_aware_model_HttpFormUrlencodedBody_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_aware_model_HttpFormUrlencodedBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_HttpFormUrlencodedBody_descriptor,
        new java.lang.String[] { "KeyValueMap", });
    internal_static_org_aware_model_HttpFormUrlencodedBody_KeyValueMapEntry_descriptor =
      internal_static_org_aware_model_HttpFormUrlencodedBody_descriptor.getNestedTypes().get(0);
    internal_static_org_aware_model_HttpFormUrlencodedBody_KeyValueMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_HttpFormUrlencodedBody_KeyValueMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_aware_model_BinaryDataBody_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_aware_model_BinaryDataBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_BinaryDataBody_descriptor,
        new java.lang.String[] { "Data", "Data", });
    internal_static_org_aware_model_Payload_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_aware_model_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_Payload_descriptor,
        new java.lang.String[] { "SpanId", "HttpPayload", "Payload", "SpanId", });
    internal_static_org_aware_model_PayloadList_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_aware_model_PayloadList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_PayloadList_descriptor,
        new java.lang.String[] { "Payloads", });
    internal_static_org_aware_model_InsertClientRecordedPayloadRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_aware_model_InsertClientRecordedPayloadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_InsertClientRecordedPayloadRequest_descriptor,
        new java.lang.String[] { "RequestPayload", "ResponsePayload", "Url", "SessionRecordingTrackingId", "CurrentUserId", "RequestPayload", "ResponsePayload", "Url", "SessionRecordingTrackingId", "CurrentUserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
