// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.aware.model;

public interface PayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.aware.model.Payload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Span ID corresponding to the payload. This is used for correlating requests with corresponding responses.
   * </pre>
   *
   * <code>optional string span_id = 1;</code>
   * @return Whether the spanId field is set.
   */
  boolean hasSpanId();
  /**
   * <pre>
   * Span ID corresponding to the payload. This is used for correlating requests with corresponding responses.
   * </pre>
   *
   * <code>optional string span_id = 1;</code>
   * @return The spanId.
   */
  java.lang.String getSpanId();
  /**
   * <pre>
   * Span ID corresponding to the payload. This is used for correlating requests with corresponding responses.
   * </pre>
   *
   * <code>optional string span_id = 1;</code>
   * @return The bytes for spanId.
   */
  com.google.protobuf.ByteString
      getSpanIdBytes();

  /**
   * <code>.org.aware.model.HttpPayload http_payload = 2;</code>
   * @return Whether the httpPayload field is set.
   */
  boolean hasHttpPayload();
  /**
   * <code>.org.aware.model.HttpPayload http_payload = 2;</code>
   * @return The httpPayload.
   */
  org.aware.model.HttpPayload getHttpPayload();
  /**
   * <code>.org.aware.model.HttpPayload http_payload = 2;</code>
   */
  org.aware.model.HttpPayloadOrBuilder getHttpPayloadOrBuilder();

  public org.aware.model.Payload.PayloadCase getPayloadCase();
}
