// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.aware.model;

public interface PayloadListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.aware.model.PayloadList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.aware.model.Payload payloads = 1;</code>
   */
  java.util.List<org.aware.model.Payload> 
      getPayloadsList();
  /**
   * <code>repeated .org.aware.model.Payload payloads = 1;</code>
   */
  org.aware.model.Payload getPayloads(int index);
  /**
   * <code>repeated .org.aware.model.Payload payloads = 1;</code>
   */
  int getPayloadsCount();
  /**
   * <code>repeated .org.aware.model.Payload payloads = 1;</code>
   */
  java.util.List<? extends org.aware.model.PayloadOrBuilder> 
      getPayloadsOrBuilderList();
  /**
   * <code>repeated .org.aware.model.Payload payloads = 1;</code>
   */
  org.aware.model.PayloadOrBuilder getPayloadsOrBuilder(
      int index);
}
