// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.aware.model;

public interface HttpPayloadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.aware.model.HttpPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */
  int getHeaderMapCount();
  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */
  boolean containsHeaderMap(
      java.lang.String key);
  /**
   * Use {@link #getHeaderMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getHeaderMap();
  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getHeaderMapMap();
  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */
  /* nullable */
java.lang.String getHeaderMapOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; header_map = 1;</code>
   */
  java.lang.String getHeaderMapOrThrow(
      java.lang.String key);

  /**
   * <code>string json_body = 2;</code>
   * @return Whether the jsonBody field is set.
   */
  boolean hasJsonBody();
  /**
   * <code>string json_body = 2;</code>
   * @return The jsonBody.
   */
  java.lang.String getJsonBody();
  /**
   * <code>string json_body = 2;</code>
   * @return The bytes for jsonBody.
   */
  com.google.protobuf.ByteString
      getJsonBodyBytes();

  public org.aware.model.HttpPayload.BodyCase getBodyCase();
}
