// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.aware.model;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_HttpPayload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_HttpPayload_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_HttpPayload_HeaderMapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_HttpPayload_HeaderMapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_aware_model_Payload_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_aware_model_Payload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\022\017org.aware.model\"\235\001\n\013HttpP" +
      "ayload\022?\n\nheader_map\030\001 \003(\0132+.org.aware.m" +
      "odel.HttpPayload.HeaderMapEntry\022\023\n\tjson_" +
      "body\030\002 \001(\tH\000\0320\n\016HeaderMapEntry\022\013\n\003key\030\001 " +
      "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B\006\n\004body\"l\n\007Payloa" +
      "d\022\024\n\007span_id\030\001 \001(\tH\001\210\001\001\0224\n\014http_payload\030" +
      "\002 \001(\0132\034.org.aware.model.HttpPayloadH\000B\t\n" +
      "\007payloadB\n\n\010_span_idB\032\n\017org.aware.modelB" +
      "\005ModelP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_aware_model_HttpPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_aware_model_HttpPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_HttpPayload_descriptor,
        new java.lang.String[] { "HeaderMap", "JsonBody", "Body", });
    internal_static_org_aware_model_HttpPayload_HeaderMapEntry_descriptor =
      internal_static_org_aware_model_HttpPayload_descriptor.getNestedTypes().get(0);
    internal_static_org_aware_model_HttpPayload_HeaderMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_HttpPayload_HeaderMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_org_aware_model_Payload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_aware_model_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_aware_model_Payload_descriptor,
        new java.lang.String[] { "SpanId", "HttpPayload", "Payload", "SpanId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
