// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.aware.model;

/**
 * Protobuf type {@code org.aware.model.PayloadList}
 */
public final class PayloadList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.aware.model.PayloadList)
    PayloadListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PayloadList.newBuilder() to construct.
  private PayloadList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PayloadList() {
    payloads_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PayloadList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.aware.model.Model.internal_static_org_aware_model_PayloadList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.aware.model.Model.internal_static_org_aware_model_PayloadList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.aware.model.PayloadList.class, org.aware.model.PayloadList.Builder.class);
  }

  public static final int PAYLOADS_FIELD_NUMBER = 1;
  private java.util.List<org.aware.model.Payload> payloads_;
  /**
   * <code>repeated .org.aware.model.Payload payloads = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.aware.model.Payload> getPayloadsList() {
    return payloads_;
  }
  /**
   * <code>repeated .org.aware.model.Payload payloads = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.aware.model.PayloadOrBuilder> 
      getPayloadsOrBuilderList() {
    return payloads_;
  }
  /**
   * <code>repeated .org.aware.model.Payload payloads = 1;</code>
   */
  @java.lang.Override
  public int getPayloadsCount() {
    return payloads_.size();
  }
  /**
   * <code>repeated .org.aware.model.Payload payloads = 1;</code>
   */
  @java.lang.Override
  public org.aware.model.Payload getPayloads(int index) {
    return payloads_.get(index);
  }
  /**
   * <code>repeated .org.aware.model.Payload payloads = 1;</code>
   */
  @java.lang.Override
  public org.aware.model.PayloadOrBuilder getPayloadsOrBuilder(
      int index) {
    return payloads_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < payloads_.size(); i++) {
      output.writeMessage(1, payloads_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < payloads_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, payloads_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.aware.model.PayloadList)) {
      return super.equals(obj);
    }
    org.aware.model.PayloadList other = (org.aware.model.PayloadList) obj;

    if (!getPayloadsList()
        .equals(other.getPayloadsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPayloadsCount() > 0) {
      hash = (37 * hash) + PAYLOADS_FIELD_NUMBER;
      hash = (53 * hash) + getPayloadsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.aware.model.PayloadList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.aware.model.PayloadList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.aware.model.PayloadList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.aware.model.PayloadList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.aware.model.PayloadList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.aware.model.PayloadList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.aware.model.PayloadList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.aware.model.PayloadList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.aware.model.PayloadList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.aware.model.PayloadList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.aware.model.PayloadList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.aware.model.PayloadList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.aware.model.PayloadList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.aware.model.PayloadList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.aware.model.PayloadList)
      org.aware.model.PayloadListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.aware.model.Model.internal_static_org_aware_model_PayloadList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.aware.model.Model.internal_static_org_aware_model_PayloadList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.aware.model.PayloadList.class, org.aware.model.PayloadList.Builder.class);
    }

    // Construct using org.aware.model.PayloadList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (payloadsBuilder_ == null) {
        payloads_ = java.util.Collections.emptyList();
      } else {
        payloads_ = null;
        payloadsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.aware.model.Model.internal_static_org_aware_model_PayloadList_descriptor;
    }

    @java.lang.Override
    public org.aware.model.PayloadList getDefaultInstanceForType() {
      return org.aware.model.PayloadList.getDefaultInstance();
    }

    @java.lang.Override
    public org.aware.model.PayloadList build() {
      org.aware.model.PayloadList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.aware.model.PayloadList buildPartial() {
      org.aware.model.PayloadList result = new org.aware.model.PayloadList(this);
      int from_bitField0_ = bitField0_;
      if (payloadsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          payloads_ = java.util.Collections.unmodifiableList(payloads_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.payloads_ = payloads_;
      } else {
        result.payloads_ = payloadsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.aware.model.PayloadList) {
        return mergeFrom((org.aware.model.PayloadList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.aware.model.PayloadList other) {
      if (other == org.aware.model.PayloadList.getDefaultInstance()) return this;
      if (payloadsBuilder_ == null) {
        if (!other.payloads_.isEmpty()) {
          if (payloads_.isEmpty()) {
            payloads_ = other.payloads_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePayloadsIsMutable();
            payloads_.addAll(other.payloads_);
          }
          onChanged();
        }
      } else {
        if (!other.payloads_.isEmpty()) {
          if (payloadsBuilder_.isEmpty()) {
            payloadsBuilder_.dispose();
            payloadsBuilder_ = null;
            payloads_ = other.payloads_;
            bitField0_ = (bitField0_ & ~0x00000001);
            payloadsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPayloadsFieldBuilder() : null;
          } else {
            payloadsBuilder_.addAllMessages(other.payloads_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.aware.model.Payload m =
                  input.readMessage(
                      org.aware.model.Payload.parser(),
                      extensionRegistry);
              if (payloadsBuilder_ == null) {
                ensurePayloadsIsMutable();
                payloads_.add(m);
              } else {
                payloadsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.aware.model.Payload> payloads_ =
      java.util.Collections.emptyList();
    private void ensurePayloadsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        payloads_ = new java.util.ArrayList<org.aware.model.Payload>(payloads_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.aware.model.Payload, org.aware.model.Payload.Builder, org.aware.model.PayloadOrBuilder> payloadsBuilder_;

    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public java.util.List<org.aware.model.Payload> getPayloadsList() {
      if (payloadsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(payloads_);
      } else {
        return payloadsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public int getPayloadsCount() {
      if (payloadsBuilder_ == null) {
        return payloads_.size();
      } else {
        return payloadsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public org.aware.model.Payload getPayloads(int index) {
      if (payloadsBuilder_ == null) {
        return payloads_.get(index);
      } else {
        return payloadsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public Builder setPayloads(
        int index, org.aware.model.Payload value) {
      if (payloadsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadsIsMutable();
        payloads_.set(index, value);
        onChanged();
      } else {
        payloadsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public Builder setPayloads(
        int index, org.aware.model.Payload.Builder builderForValue) {
      if (payloadsBuilder_ == null) {
        ensurePayloadsIsMutable();
        payloads_.set(index, builderForValue.build());
        onChanged();
      } else {
        payloadsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public Builder addPayloads(org.aware.model.Payload value) {
      if (payloadsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadsIsMutable();
        payloads_.add(value);
        onChanged();
      } else {
        payloadsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public Builder addPayloads(
        int index, org.aware.model.Payload value) {
      if (payloadsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadsIsMutable();
        payloads_.add(index, value);
        onChanged();
      } else {
        payloadsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public Builder addPayloads(
        org.aware.model.Payload.Builder builderForValue) {
      if (payloadsBuilder_ == null) {
        ensurePayloadsIsMutable();
        payloads_.add(builderForValue.build());
        onChanged();
      } else {
        payloadsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public Builder addPayloads(
        int index, org.aware.model.Payload.Builder builderForValue) {
      if (payloadsBuilder_ == null) {
        ensurePayloadsIsMutable();
        payloads_.add(index, builderForValue.build());
        onChanged();
      } else {
        payloadsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public Builder addAllPayloads(
        java.lang.Iterable<? extends org.aware.model.Payload> values) {
      if (payloadsBuilder_ == null) {
        ensurePayloadsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, payloads_);
        onChanged();
      } else {
        payloadsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public Builder clearPayloads() {
      if (payloadsBuilder_ == null) {
        payloads_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        payloadsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public Builder removePayloads(int index) {
      if (payloadsBuilder_ == null) {
        ensurePayloadsIsMutable();
        payloads_.remove(index);
        onChanged();
      } else {
        payloadsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public org.aware.model.Payload.Builder getPayloadsBuilder(
        int index) {
      return getPayloadsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public org.aware.model.PayloadOrBuilder getPayloadsOrBuilder(
        int index) {
      if (payloadsBuilder_ == null) {
        return payloads_.get(index);  } else {
        return payloadsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public java.util.List<? extends org.aware.model.PayloadOrBuilder> 
         getPayloadsOrBuilderList() {
      if (payloadsBuilder_ != null) {
        return payloadsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(payloads_);
      }
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public org.aware.model.Payload.Builder addPayloadsBuilder() {
      return getPayloadsFieldBuilder().addBuilder(
          org.aware.model.Payload.getDefaultInstance());
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public org.aware.model.Payload.Builder addPayloadsBuilder(
        int index) {
      return getPayloadsFieldBuilder().addBuilder(
          index, org.aware.model.Payload.getDefaultInstance());
    }
    /**
     * <code>repeated .org.aware.model.Payload payloads = 1;</code>
     */
    public java.util.List<org.aware.model.Payload.Builder> 
         getPayloadsBuilderList() {
      return getPayloadsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.aware.model.Payload, org.aware.model.Payload.Builder, org.aware.model.PayloadOrBuilder> 
        getPayloadsFieldBuilder() {
      if (payloadsBuilder_ == null) {
        payloadsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.aware.model.Payload, org.aware.model.Payload.Builder, org.aware.model.PayloadOrBuilder>(
                payloads_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        payloads_ = null;
      }
      return payloadsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.aware.model.PayloadList)
  }

  // @@protoc_insertion_point(class_scope:org.aware.model.PayloadList)
  private static final org.aware.model.PayloadList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.aware.model.PayloadList();
  }

  public static org.aware.model.PayloadList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PayloadList>
      PARSER = new com.google.protobuf.AbstractParser<PayloadList>() {
    @java.lang.Override
    public PayloadList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PayloadList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PayloadList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.aware.model.PayloadList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

