// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.testchimp.model;

public interface BinaryDataBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.testchimp.model.BinaryDataBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes data = 1;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>optional bytes data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
