// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.testchimp.model;

/**
 * Protobuf type {@code org.testchimp.model.InsertClientRecordedPayloadRequest}
 */
public final class InsertClientRecordedPayloadRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.testchimp.model.InsertClientRecordedPayloadRequest)
    InsertClientRecordedPayloadRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InsertClientRecordedPayloadRequest.newBuilder() to construct.
  private InsertClientRecordedPayloadRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InsertClientRecordedPayloadRequest() {
    url_ = "";
    sessionRecordingTrackingId_ = "";
    currentUserId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new InsertClientRecordedPayloadRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.testchimp.model.Model.internal_static_org_testchimp_model_InsertClientRecordedPayloadRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.testchimp.model.Model.internal_static_org_testchimp_model_InsertClientRecordedPayloadRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.testchimp.model.InsertClientRecordedPayloadRequest.class, org.testchimp.model.InsertClientRecordedPayloadRequest.Builder.class);
  }

  private int bitField0_;
  public static final int REQUEST_PAYLOAD_FIELD_NUMBER = 1;
  private org.testchimp.model.Payload requestPayload_;
  /**
   * <code>optional .org.testchimp.model.Payload request_payload = 1;</code>
   * @return Whether the requestPayload field is set.
   */
  @java.lang.Override
  public boolean hasRequestPayload() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .org.testchimp.model.Payload request_payload = 1;</code>
   * @return The requestPayload.
   */
  @java.lang.Override
  public org.testchimp.model.Payload getRequestPayload() {
    return requestPayload_ == null ? org.testchimp.model.Payload.getDefaultInstance() : requestPayload_;
  }
  /**
   * <code>optional .org.testchimp.model.Payload request_payload = 1;</code>
   */
  @java.lang.Override
  public org.testchimp.model.PayloadOrBuilder getRequestPayloadOrBuilder() {
    return requestPayload_ == null ? org.testchimp.model.Payload.getDefaultInstance() : requestPayload_;
  }

  public static final int RESPONSE_PAYLOAD_FIELD_NUMBER = 2;
  private org.testchimp.model.Payload responsePayload_;
  /**
   * <code>optional .org.testchimp.model.Payload response_payload = 2;</code>
   * @return Whether the responsePayload field is set.
   */
  @java.lang.Override
  public boolean hasResponsePayload() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .org.testchimp.model.Payload response_payload = 2;</code>
   * @return The responsePayload.
   */
  @java.lang.Override
  public org.testchimp.model.Payload getResponsePayload() {
    return responsePayload_ == null ? org.testchimp.model.Payload.getDefaultInstance() : responsePayload_;
  }
  /**
   * <code>optional .org.testchimp.model.Payload response_payload = 2;</code>
   */
  @java.lang.Override
  public org.testchimp.model.PayloadOrBuilder getResponsePayloadOrBuilder() {
    return responsePayload_ == null ? org.testchimp.model.Payload.getDefaultInstance() : responsePayload_;
  }

  public static final int URL_FIELD_NUMBER = 3;
  private volatile java.lang.Object url_;
  /**
   * <code>optional string url = 3;</code>
   * @return Whether the url field is set.
   */
  @java.lang.Override
  public boolean hasUrl() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string url = 3;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <code>optional string url = 3;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SESSION_RECORDING_TRACKING_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object sessionRecordingTrackingId_;
  /**
   * <code>optional string session_recording_tracking_id = 4;</code>
   * @return Whether the sessionRecordingTrackingId field is set.
   */
  @java.lang.Override
  public boolean hasSessionRecordingTrackingId() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string session_recording_tracking_id = 4;</code>
   * @return The sessionRecordingTrackingId.
   */
  @java.lang.Override
  public java.lang.String getSessionRecordingTrackingId() {
    java.lang.Object ref = sessionRecordingTrackingId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sessionRecordingTrackingId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string session_recording_tracking_id = 4;</code>
   * @return The bytes for sessionRecordingTrackingId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSessionRecordingTrackingIdBytes() {
    java.lang.Object ref = sessionRecordingTrackingId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sessionRecordingTrackingId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENT_USER_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object currentUserId_;
  /**
   * <code>optional string current_user_id = 5;</code>
   * @return Whether the currentUserId field is set.
   */
  @java.lang.Override
  public boolean hasCurrentUserId() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string current_user_id = 5;</code>
   * @return The currentUserId.
   */
  @java.lang.Override
  public java.lang.String getCurrentUserId() {
    java.lang.Object ref = currentUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentUserId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string current_user_id = 5;</code>
   * @return The bytes for currentUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrentUserIdBytes() {
    java.lang.Object ref = currentUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getRequestPayload());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getResponsePayload());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, url_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sessionRecordingTrackingId_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, currentUserId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRequestPayload());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getResponsePayload());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, url_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sessionRecordingTrackingId_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, currentUserId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.testchimp.model.InsertClientRecordedPayloadRequest)) {
      return super.equals(obj);
    }
    org.testchimp.model.InsertClientRecordedPayloadRequest other = (org.testchimp.model.InsertClientRecordedPayloadRequest) obj;

    if (hasRequestPayload() != other.hasRequestPayload()) return false;
    if (hasRequestPayload()) {
      if (!getRequestPayload()
          .equals(other.getRequestPayload())) return false;
    }
    if (hasResponsePayload() != other.hasResponsePayload()) return false;
    if (hasResponsePayload()) {
      if (!getResponsePayload()
          .equals(other.getResponsePayload())) return false;
    }
    if (hasUrl() != other.hasUrl()) return false;
    if (hasUrl()) {
      if (!getUrl()
          .equals(other.getUrl())) return false;
    }
    if (hasSessionRecordingTrackingId() != other.hasSessionRecordingTrackingId()) return false;
    if (hasSessionRecordingTrackingId()) {
      if (!getSessionRecordingTrackingId()
          .equals(other.getSessionRecordingTrackingId())) return false;
    }
    if (hasCurrentUserId() != other.hasCurrentUserId()) return false;
    if (hasCurrentUserId()) {
      if (!getCurrentUserId()
          .equals(other.getCurrentUserId())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRequestPayload()) {
      hash = (37 * hash) + REQUEST_PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getRequestPayload().hashCode();
    }
    if (hasResponsePayload()) {
      hash = (37 * hash) + RESPONSE_PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getResponsePayload().hashCode();
    }
    if (hasUrl()) {
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
    }
    if (hasSessionRecordingTrackingId()) {
      hash = (37 * hash) + SESSION_RECORDING_TRACKING_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionRecordingTrackingId().hashCode();
    }
    if (hasCurrentUserId()) {
      hash = (37 * hash) + CURRENT_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentUserId().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.testchimp.model.InsertClientRecordedPayloadRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.testchimp.model.InsertClientRecordedPayloadRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.testchimp.model.InsertClientRecordedPayloadRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.testchimp.model.InsertClientRecordedPayloadRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.testchimp.model.InsertClientRecordedPayloadRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.testchimp.model.InsertClientRecordedPayloadRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.testchimp.model.InsertClientRecordedPayloadRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.testchimp.model.InsertClientRecordedPayloadRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.testchimp.model.InsertClientRecordedPayloadRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.testchimp.model.InsertClientRecordedPayloadRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.testchimp.model.InsertClientRecordedPayloadRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.testchimp.model.InsertClientRecordedPayloadRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.testchimp.model.InsertClientRecordedPayloadRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.testchimp.model.InsertClientRecordedPayloadRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.testchimp.model.InsertClientRecordedPayloadRequest)
      org.testchimp.model.InsertClientRecordedPayloadRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.testchimp.model.Model.internal_static_org_testchimp_model_InsertClientRecordedPayloadRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.testchimp.model.Model.internal_static_org_testchimp_model_InsertClientRecordedPayloadRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.testchimp.model.InsertClientRecordedPayloadRequest.class, org.testchimp.model.InsertClientRecordedPayloadRequest.Builder.class);
    }

    // Construct using org.testchimp.model.InsertClientRecordedPayloadRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRequestPayloadFieldBuilder();
        getResponsePayloadFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (requestPayloadBuilder_ == null) {
        requestPayload_ = null;
      } else {
        requestPayloadBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (responsePayloadBuilder_ == null) {
        responsePayload_ = null;
      } else {
        responsePayloadBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      url_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      sessionRecordingTrackingId_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      currentUserId_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.testchimp.model.Model.internal_static_org_testchimp_model_InsertClientRecordedPayloadRequest_descriptor;
    }

    @java.lang.Override
    public org.testchimp.model.InsertClientRecordedPayloadRequest getDefaultInstanceForType() {
      return org.testchimp.model.InsertClientRecordedPayloadRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.testchimp.model.InsertClientRecordedPayloadRequest build() {
      org.testchimp.model.InsertClientRecordedPayloadRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.testchimp.model.InsertClientRecordedPayloadRequest buildPartial() {
      org.testchimp.model.InsertClientRecordedPayloadRequest result = new org.testchimp.model.InsertClientRecordedPayloadRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (requestPayloadBuilder_ == null) {
          result.requestPayload_ = requestPayload_;
        } else {
          result.requestPayload_ = requestPayloadBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (responsePayloadBuilder_ == null) {
          result.responsePayload_ = responsePayload_;
        } else {
          result.responsePayload_ = responsePayloadBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.url_ = url_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.sessionRecordingTrackingId_ = sessionRecordingTrackingId_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.currentUserId_ = currentUserId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.testchimp.model.InsertClientRecordedPayloadRequest) {
        return mergeFrom((org.testchimp.model.InsertClientRecordedPayloadRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.testchimp.model.InsertClientRecordedPayloadRequest other) {
      if (other == org.testchimp.model.InsertClientRecordedPayloadRequest.getDefaultInstance()) return this;
      if (other.hasRequestPayload()) {
        mergeRequestPayload(other.getRequestPayload());
      }
      if (other.hasResponsePayload()) {
        mergeResponsePayload(other.getResponsePayload());
      }
      if (other.hasUrl()) {
        bitField0_ |= 0x00000004;
        url_ = other.url_;
        onChanged();
      }
      if (other.hasSessionRecordingTrackingId()) {
        bitField0_ |= 0x00000008;
        sessionRecordingTrackingId_ = other.sessionRecordingTrackingId_;
        onChanged();
      }
      if (other.hasCurrentUserId()) {
        bitField0_ |= 0x00000010;
        currentUserId_ = other.currentUserId_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getRequestPayloadFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getResponsePayloadFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              url_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              sessionRecordingTrackingId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              currentUserId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.testchimp.model.Payload requestPayload_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.testchimp.model.Payload, org.testchimp.model.Payload.Builder, org.testchimp.model.PayloadOrBuilder> requestPayloadBuilder_;
    /**
     * <code>optional .org.testchimp.model.Payload request_payload = 1;</code>
     * @return Whether the requestPayload field is set.
     */
    public boolean hasRequestPayload() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .org.testchimp.model.Payload request_payload = 1;</code>
     * @return The requestPayload.
     */
    public org.testchimp.model.Payload getRequestPayload() {
      if (requestPayloadBuilder_ == null) {
        return requestPayload_ == null ? org.testchimp.model.Payload.getDefaultInstance() : requestPayload_;
      } else {
        return requestPayloadBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .org.testchimp.model.Payload request_payload = 1;</code>
     */
    public Builder setRequestPayload(org.testchimp.model.Payload value) {
      if (requestPayloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestPayload_ = value;
        onChanged();
      } else {
        requestPayloadBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .org.testchimp.model.Payload request_payload = 1;</code>
     */
    public Builder setRequestPayload(
        org.testchimp.model.Payload.Builder builderForValue) {
      if (requestPayloadBuilder_ == null) {
        requestPayload_ = builderForValue.build();
        onChanged();
      } else {
        requestPayloadBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .org.testchimp.model.Payload request_payload = 1;</code>
     */
    public Builder mergeRequestPayload(org.testchimp.model.Payload value) {
      if (requestPayloadBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            requestPayload_ != null &&
            requestPayload_ != org.testchimp.model.Payload.getDefaultInstance()) {
          requestPayload_ =
            org.testchimp.model.Payload.newBuilder(requestPayload_).mergeFrom(value).buildPartial();
        } else {
          requestPayload_ = value;
        }
        onChanged();
      } else {
        requestPayloadBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .org.testchimp.model.Payload request_payload = 1;</code>
     */
    public Builder clearRequestPayload() {
      if (requestPayloadBuilder_ == null) {
        requestPayload_ = null;
        onChanged();
      } else {
        requestPayloadBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .org.testchimp.model.Payload request_payload = 1;</code>
     */
    public org.testchimp.model.Payload.Builder getRequestPayloadBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getRequestPayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .org.testchimp.model.Payload request_payload = 1;</code>
     */
    public org.testchimp.model.PayloadOrBuilder getRequestPayloadOrBuilder() {
      if (requestPayloadBuilder_ != null) {
        return requestPayloadBuilder_.getMessageOrBuilder();
      } else {
        return requestPayload_ == null ?
            org.testchimp.model.Payload.getDefaultInstance() : requestPayload_;
      }
    }
    /**
     * <code>optional .org.testchimp.model.Payload request_payload = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.testchimp.model.Payload, org.testchimp.model.Payload.Builder, org.testchimp.model.PayloadOrBuilder> 
        getRequestPayloadFieldBuilder() {
      if (requestPayloadBuilder_ == null) {
        requestPayloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.testchimp.model.Payload, org.testchimp.model.Payload.Builder, org.testchimp.model.PayloadOrBuilder>(
                getRequestPayload(),
                getParentForChildren(),
                isClean());
        requestPayload_ = null;
      }
      return requestPayloadBuilder_;
    }

    private org.testchimp.model.Payload responsePayload_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.testchimp.model.Payload, org.testchimp.model.Payload.Builder, org.testchimp.model.PayloadOrBuilder> responsePayloadBuilder_;
    /**
     * <code>optional .org.testchimp.model.Payload response_payload = 2;</code>
     * @return Whether the responsePayload field is set.
     */
    public boolean hasResponsePayload() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .org.testchimp.model.Payload response_payload = 2;</code>
     * @return The responsePayload.
     */
    public org.testchimp.model.Payload getResponsePayload() {
      if (responsePayloadBuilder_ == null) {
        return responsePayload_ == null ? org.testchimp.model.Payload.getDefaultInstance() : responsePayload_;
      } else {
        return responsePayloadBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .org.testchimp.model.Payload response_payload = 2;</code>
     */
    public Builder setResponsePayload(org.testchimp.model.Payload value) {
      if (responsePayloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        responsePayload_ = value;
        onChanged();
      } else {
        responsePayloadBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .org.testchimp.model.Payload response_payload = 2;</code>
     */
    public Builder setResponsePayload(
        org.testchimp.model.Payload.Builder builderForValue) {
      if (responsePayloadBuilder_ == null) {
        responsePayload_ = builderForValue.build();
        onChanged();
      } else {
        responsePayloadBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .org.testchimp.model.Payload response_payload = 2;</code>
     */
    public Builder mergeResponsePayload(org.testchimp.model.Payload value) {
      if (responsePayloadBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            responsePayload_ != null &&
            responsePayload_ != org.testchimp.model.Payload.getDefaultInstance()) {
          responsePayload_ =
            org.testchimp.model.Payload.newBuilder(responsePayload_).mergeFrom(value).buildPartial();
        } else {
          responsePayload_ = value;
        }
        onChanged();
      } else {
        responsePayloadBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .org.testchimp.model.Payload response_payload = 2;</code>
     */
    public Builder clearResponsePayload() {
      if (responsePayloadBuilder_ == null) {
        responsePayload_ = null;
        onChanged();
      } else {
        responsePayloadBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .org.testchimp.model.Payload response_payload = 2;</code>
     */
    public org.testchimp.model.Payload.Builder getResponsePayloadBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getResponsePayloadFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .org.testchimp.model.Payload response_payload = 2;</code>
     */
    public org.testchimp.model.PayloadOrBuilder getResponsePayloadOrBuilder() {
      if (responsePayloadBuilder_ != null) {
        return responsePayloadBuilder_.getMessageOrBuilder();
      } else {
        return responsePayload_ == null ?
            org.testchimp.model.Payload.getDefaultInstance() : responsePayload_;
      }
    }
    /**
     * <code>optional .org.testchimp.model.Payload response_payload = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.testchimp.model.Payload, org.testchimp.model.Payload.Builder, org.testchimp.model.PayloadOrBuilder> 
        getResponsePayloadFieldBuilder() {
      if (responsePayloadBuilder_ == null) {
        responsePayloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.testchimp.model.Payload, org.testchimp.model.Payload.Builder, org.testchimp.model.PayloadOrBuilder>(
                getResponsePayload(),
                getParentForChildren(),
                isClean());
        responsePayload_ = null;
      }
      return responsePayloadBuilder_;
    }

    private java.lang.Object url_ = "";
    /**
     * <code>optional string url = 3;</code>
     * @return Whether the url field is set.
     */
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string url = 3;</code>
     * @return The url.
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string url = 3;</code>
     * @return The bytes for url.
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string url = 3;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      url_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string url = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      bitField0_ = (bitField0_ & ~0x00000004);
      url_ = getDefaultInstance().getUrl();
      onChanged();
      return this;
    }
    /**
     * <code>optional string url = 3;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      url_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sessionRecordingTrackingId_ = "";
    /**
     * <code>optional string session_recording_tracking_id = 4;</code>
     * @return Whether the sessionRecordingTrackingId field is set.
     */
    public boolean hasSessionRecordingTrackingId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string session_recording_tracking_id = 4;</code>
     * @return The sessionRecordingTrackingId.
     */
    public java.lang.String getSessionRecordingTrackingId() {
      java.lang.Object ref = sessionRecordingTrackingId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionRecordingTrackingId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string session_recording_tracking_id = 4;</code>
     * @return The bytes for sessionRecordingTrackingId.
     */
    public com.google.protobuf.ByteString
        getSessionRecordingTrackingIdBytes() {
      java.lang.Object ref = sessionRecordingTrackingId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionRecordingTrackingId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string session_recording_tracking_id = 4;</code>
     * @param value The sessionRecordingTrackingId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionRecordingTrackingId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      sessionRecordingTrackingId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string session_recording_tracking_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionRecordingTrackingId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sessionRecordingTrackingId_ = getDefaultInstance().getSessionRecordingTrackingId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string session_recording_tracking_id = 4;</code>
     * @param value The bytes for sessionRecordingTrackingId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionRecordingTrackingIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000008;
      sessionRecordingTrackingId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object currentUserId_ = "";
    /**
     * <code>optional string current_user_id = 5;</code>
     * @return Whether the currentUserId field is set.
     */
    public boolean hasCurrentUserId() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string current_user_id = 5;</code>
     * @return The currentUserId.
     */
    public java.lang.String getCurrentUserId() {
      java.lang.Object ref = currentUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string current_user_id = 5;</code>
     * @return The bytes for currentUserId.
     */
    public com.google.protobuf.ByteString
        getCurrentUserIdBytes() {
      java.lang.Object ref = currentUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string current_user_id = 5;</code>
     * @param value The currentUserId to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      currentUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string current_user_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentUserId() {
      bitField0_ = (bitField0_ & ~0x00000010);
      currentUserId_ = getDefaultInstance().getCurrentUserId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string current_user_id = 5;</code>
     * @param value The bytes for currentUserId to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000010;
      currentUserId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.testchimp.model.InsertClientRecordedPayloadRequest)
  }

  // @@protoc_insertion_point(class_scope:org.testchimp.model.InsertClientRecordedPayloadRequest)
  private static final org.testchimp.model.InsertClientRecordedPayloadRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.testchimp.model.InsertClientRecordedPayloadRequest();
  }

  public static org.testchimp.model.InsertClientRecordedPayloadRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InsertClientRecordedPayloadRequest>
      PARSER = new com.google.protobuf.AbstractParser<InsertClientRecordedPayloadRequest>() {
    @java.lang.Override
    public InsertClientRecordedPayloadRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InsertClientRecordedPayloadRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InsertClientRecordedPayloadRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.testchimp.model.InsertClientRecordedPayloadRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

