// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package org.testchimp.model;

public interface PayloadListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.testchimp.model.PayloadList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.testchimp.model.Payload payloads = 1;</code>
   */
  java.util.List<org.testchimp.model.Payload> 
      getPayloadsList();
  /**
   * <code>repeated .org.testchimp.model.Payload payloads = 1;</code>
   */
  org.testchimp.model.Payload getPayloads(int index);
  /**
   * <code>repeated .org.testchimp.model.Payload payloads = 1;</code>
   */
  int getPayloadsCount();
  /**
   * <code>repeated .org.testchimp.model.Payload payloads = 1;</code>
   */
  java.util.List<? extends org.testchimp.model.PayloadOrBuilder> 
      getPayloadsOrBuilderList();
  /**
   * <code>repeated .org.testchimp.model.Payload payloads = 1;</code>
   */
  org.testchimp.model.PayloadOrBuilder getPayloadsOrBuilder(
      int index);
}
