name: 'TestChimp AI Test Repair'
description: 'Run tests with AI-powered repair capabilities'
author: 'TestChimp'

inputs:
  test-directory:
    description: 'Directory to scan for TestChimp managed tests'
    required: false
    default: 'tests'
  
  recursive:
    description: 'Scan subdirectories recursively'
    required: false
    default: 'true'
  
  include-pattern:
    description: 'File patterns to include (glob)'
    required: false
    default: '**/*.spec.{js,ts}'
  
  exclude-pattern:
    description: 'File patterns to exclude (glob)'
    required: false
    default: '**/node_modules/**'
  
  mode:
    description: 'Execution mode (RUN_EXACTLY or RUN_WITH_AI_REPAIR)'
    required: false
    default: 'RUN_WITH_AI_REPAIR'
  
  deflake-runs:
    description: 'Number of deflake runs to attempt'
    required: false
    default: '2'
  
  headless:
    description: 'Run browser in headless mode'
    required: false
    default: 'true'
  
  api-key:
    description: 'TestChimp project API key (required for CI/CD authentication)'
    required: true
  
  project-id:
    description: 'TestChimp project ID (required for CI/CD authentication)'
    required: true
  
  success-criteria:
    description: 'Test success criteria (ORIGINAL_SUCCESS or REPAIR_SUCCESS_WITH_CONFIDENCE)'
    required: false
    default: 'ORIGINAL_SUCCESS'
  
  repair-confidence-threshold:
    description: 'Minimum confidence score required for repair success (1-5)'
    required: false
    default: '4'

outputs:
  status:
    description: 'Overall execution status'
  test-count:
    description: 'Number of tests executed'
  success-count:
    description: 'Number of successful tests'
  failure-count:
    description: 'Number of failed tests'
  repaired-count:
    description: 'Number of tests that were repaired'
  repaired-above-threshold:
    description: 'Number of tests repaired with confidence above threshold'
  repaired-below-threshold:
    description: 'Number of tests repaired with confidence below threshold'
  success-criteria-used:
    description: 'Success criteria that was applied (ORIGINAL_SUCCESS or REPAIR_SUCCESS_WITH_CONFIDENCE)'

runs:
  using: 'node20'
  main: 'dist/index.js'
